'use strict';
// species.js - 全ルート種データ（PHASE 1 分離版）

const SPECIES = {

// ==================== リクガメルート ====================
land: [
  { name: 'ロシアリクガメ', latin: 'Testudo (Agrionemys) horsfieldii', emoji: '🏔️', difficulty: '入門〜中級', size: 'M（15〜20cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: 'リクガメ入門の定番。乾燥した環境を好み、60〜90cmのケージから始められます。好奇心が旺盛でなつきやすく、初心者にも人気。CITES IIですので国内CBのインボイス付き個体を選びましょう。',
    specs: { '最大甲長': '20cm前後', '主な食事': '野草・野菜', '水容量': '浅め水入れ', '温度': '25〜32℃' },
    coreSpecs: { size: '20cm前後', temp: '25〜32℃', lifespan: '40〜80年', diet: '草食（野草・野菜中心）' },
    extraSpecs: {},
    links: [{ label: '乾燥系リクガメ 飼育ガイド', href: '../guide-dry.html' }], asin: null,
    slug: 'russian-tortoise', hasPage: true,
    match: function(s){ return (s.compact||0) >= 2 && (s.dry||0) >= 2; },
    score: function(s){ return (s.compact||0)+(s.dry||0)+(s.beginner||0)+(s.herbivore||0)+(s.eu_cb||0); }
  },
  { name: 'ヘルマンリクガメ（ヒガシ亜種）', latin: 'Testudo hermanni boettgeri', emoji: '🌿', difficulty: '中級', size: 'M（15〜23cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: 'EU産CBの流通が豊富でコンディションが安定。やや湿度のある地中海環境を好み、ロシアリクガメより扱いやすいと評価する飼育者も多い。最も人気の高い地中海系リクガメ。',
    specs: { '最大甲長': '23cm', '主な食事': '野草・野菜', '水容量': '浅め水入れ', '温度': '25〜30℃' },
    coreSpecs: { size: '23cm', temp: '25〜30℃', lifespan: '50〜80年', diet: '草食（野草・野菜中心）' },
    extraSpecs: {},
    links: [{ label: '乾燥系リクガメ 飼育ガイド', href: '../guide-dry.html' }], asin: null,
    slug: 'hermann-tortoise', hasPage: true,
    match: function(s){ return (s.compact||0) >= 1 && (s.humid||0) >= 2; },
    score: function(s){ return (s.compact||0)+(s.humid||0)+(s.intermediate||0)+(s.herbivore||0)+(s.eu_cb||0); }
  },
  { name: 'ヘルマンリクガメ（ニシ亜種）', latin: 'Testudo hermanni hermanni', emoji: '🍋', difficulty: '中級', size: 'S〜M（10〜18cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: 'ヒガシ亜種より小型で黄みが強い体色が特徴。コンパクトなケージで飼育できる小型リクガメを求める中級者に向く。EU産CB流通あり。',
    specs: { '最大甲長': '18cm', '主な食事': '野草・野菜', '水容量': '浅め水入れ', '温度': '24〜29℃' },
    coreSpecs: { size: '18cm', temp: '24〜29℃', lifespan: '50〜80年', diet: '草食（野草・野菜中心）' },
    extraSpecs: {},
    links: [{ label: '乾燥系リクガメ 飼育ガイド', href: '../guide-dry.html' }], asin: null,
    slug: 'hermann-tortoise', hasPage: true,
    match: function(s){ return (s.compact||0) >= 2 && (s.humid||0) >= 1 && (s.intermediate||0) >= 1; },
    score: function(s){ return (s.compact||0)+(s.humid||0)+(s.intermediate||0)+(s.herbivore||0)+(s.eu_cb||0)+(s.small_form||0); }
  },
  { name: 'ギリシャリクガメ', latin: 'Testudo graeca', emoji: '🏛️', difficulty: '中〜上級', size: 'M（15〜25cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '亜種が多く産地によって環境適応が大きく異なります。産地情報付きCBを選ぶことが重要で、中級以上向きです。',
    specs: { '最大甲長': '25cm前後', '主な食事': '野草・野菜', '水容量': '浅め水入れ', '温度': '25〜33℃' },
    coreSpecs: { size: '25cm前後', temp: '25〜33℃', lifespan: '50〜100年', diet: '草食（野草・野菜中心）' },
    extraSpecs: {},
    links: [{ label: '乾燥系リクガメ 飼育ガイド', href: '../guide-dry.html' }], asin: null,
    slug: 'greek-tortoise', hasPage: true,
    match: function(s){ return (s.intermediate||0) >= 2 || (s.advanced||0) >= 1; },
    score: function(s){ return (s.medium||0)+(s.dry||0)+(s.intermediate||0)+(s.herbivore||0)+(s.eu_cb||0); }
  },
  { name: 'フチゾリリクガメ', latin: 'Testudo marginata', emoji: '🌊', difficulty: '中〜上級', size: 'M（25〜35cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: 'ギリシャ・サルデーニャ島産の地中海リクガメ。後部甲羅が特徴的に外側に反り返る個性的な体型。ヘルマンより大型化するが乾燥管理は同様。',
    specs: { '最大甲長': '35cm', '主な食事': '野草・野菜', '水容量': '浅め水入れ', '温度': '25〜32℃' },
    coreSpecs: { size: '35cm', temp: '25〜32℃', lifespan: '30〜80年', diet: '草食（野草・野菜中心）' },
    extraSpecs: {},
    links: [{ label: '乾燥系リクガメ 飼育ガイド', href: '../guide-dry.html' }], asin: null,
    slug: 'marginated-tortoise', hasPage: true,
    match: function(s){ return (s.medium||0) >= 2 && (s.dry||0) >= 2 && (s.intermediate||0) >= 1; },
    score: function(s){ return (s.medium||0)+(s.dry||0)+(s.intermediate||0)+(s.herbivore||0)+(s.eu_cb||0); }
  },
  { name: 'エロンガータリクガメ', latin: 'Indotestudo elongata', emoji: '🌴', difficulty: '中〜上級', size: 'M（25〜33cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '東南アジア〜インド産の森林性リクガメ。高温多湿の環境を好み、地中海系リクガメとは異なる飼育感覚が楽しい。ミスト管理がポイント。',
    specs: { '最大甲長': '33cm', '主な食事': '野草・野菜・果物少量', '水容量': '浅め水入れ', '温度': '27〜32℃' },
    coreSpecs: { size: '33cm', temp: '27〜32℃', lifespan: '30〜80年', diet: '草食（野草・野菜中心）' },
    extraSpecs: {},
    links: [{ label: '多湿系リクガメ 飼育ガイド', href: '../guide-arid.html' }], asin: null,
    slug: 'elongated-tortoise', hasPage: true,
    match: function(s){ return (s.medium||0) >= 2 && (s.humid||0) >= 2; },
    score: function(s){ return (s.medium||0)+(s.humid||0)+(s.intermediate||0)+(s.herbivore||0)+(s.asia_land||0); }
  },
  { name: 'アカアシリクガメ', latin: 'Chelonoidis carbonarius', emoji: '🦶', difficulty: '中〜上級', size: 'L（30〜40cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '赤い鱗模様が美しい南米産リクガメ。雑食性で果物や動物性タンパクも食べます。高温多湿の環境が必要で大型化するためスペースが必要。',
    specs: { '最大甲長': '40cm前後', '主な食事': '野菜・果物・動物性タンパク', '水容量': '浅め水入れ', '温度': '28〜32℃' },
    coreSpecs: { size: '40cm前後', temp: '28〜32℃', lifespan: '30〜80年', diet: '草食（野草・野菜中心）' },
    extraSpecs: {},
    links: [{ label: '多湿系リクガメ 飼育ガイド', href: '../guide-arid.html' }], asin: null,
    slug: 'red-footed-tortoise', hasPage: true,
    match: function(s){ return (s.large||0) >= 2 && (s.humid||0) >= 2; },
    score: function(s){ return (s.large||0)+(s.humid||0)+(s.intermediate||0)+(s.charisma||0); }
  },
  { name: 'チャコリクガメ', latin: 'Chelonoidis chilensis', emoji: '🌵', difficulty: '上級', size: 'M（22〜27cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '南米チャコ地方の乾燥地帯産。コンパクトなサイズで本格的な乾燥管理を楽しみたい上級者向き。WCは状態が悪いことが多くCBを強く推奨。',
    specs: { '最大甲長': '27cm', '主な食事': '野草・乾草', '水容量': '浅め水入れ', '温度': '26〜33℃' },
    coreSpecs: { size: '27cm', temp: '26〜33℃', lifespan: '30〜80年', diet: '草食（野草・野菜中心）' },
    extraSpecs: {},
    links: [{ label: '乾燥系リクガメ 飼育ガイド', href: '../guide-dry.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.compact||0) >= 1 && (s.dry||0) >= 3 && (s.advanced||0) >= 1; },
    score: function(s){ return (s.compact||0)+(s.dry||0)+(s.advanced||0)+(s.herbivore||0)+(s.small_form||0); }
  },
  { name: 'ヒョウモンガメ', latin: 'Stigmochelys pardalis', emoji: '🐆', difficulty: '上級', size: 'L（40〜65cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: 'アフリカのサバンナに生息する豹柄の大型リクガメ。広いスペースと安定した高温乾燥環境が必要。上級者のチャレンジ種として人気。',
    specs: { '最大甲長': '65cm', '主な食事': '野草・乾草中心', '水容量': '大型水入れ', '温度': '28〜35℃' },
    coreSpecs: { size: '65cm', temp: '28〜35℃', lifespan: '30〜80年', diet: '草食（野草・野菜中心）' },
    extraSpecs: {},
    links: [{ label: '乾燥系リクガメ 飼育ガイド', href: '../guide-dry.html' }], asin: null,
    slug: 'leopard-tortoise', hasPage: true,
    match: function(s){ return (s.large||0) >= 3 && (s.dry||0) >= 3; },
    score: function(s){ return (s.large||0)+(s.dry||0)+(s.advanced||0)+(s.charisma||0)*2; }
  },
  { name: 'ベルセオレガメ', latin: 'Kinixys belliana', emoji: '🔒', difficulty: '上級', size: 'M（15〜25cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: 'ヒンジバック（背甲後部が可動する）という独特の構造を持つアフリカ産リクガメ。WC個体が多く状態管理が難しい。CB個体を入手できれば中型で飼いやすい。',
    specs: { '最大甲長': '25cm', '主な食事': '野草・野菜・昆虫少量', '水容量': '水入れ', '温度': '26〜32℃' },
    coreSpecs: { size: '25cm', temp: '26〜32℃', lifespan: '30〜80年', diet: '草食（野草・野菜中心）' },
    extraSpecs: {},
    links: [{ label: '乾燥系リクガメ 飼育ガイド', href: '../guide-dry.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.advanced||0) >= 2 && (s.humid||0) >= 1; },
    score: function(s){ return (s.advanced||0)+(s.humid||0)+(s.medium||0)+(s.charisma||0)*2; }
  },
  { name: 'ケヅメリクガメ（スルカタ）', latin: 'Centrochelys sulcata', emoji: '🦏', difficulty: '上級', size: 'XL（50〜100cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '亜成体は愛らしいが成体は30〜100kgになる本格派。6畳以上の屋外放し飼いを念頭に置いた長期的な計画が必要な種です。',
    specs: { '最大甲長': '90cm超', '主な食事': '乾草・野草', '水容量': '大型水場', '温度': '30〜38℃' },
    coreSpecs: { size: '90cm超', temp: '30〜38℃', lifespan: '50〜100年', diet: '草食（野草・野菜中心）' },
    extraSpecs: {},
    links: [{ label: '乾燥系リクガメ 飼育ガイド', href: '../guide-dry.html' }], asin: null,
    slug: 'sulcata-tortoise', hasPage: true,
    match: function(s){ return (s.large||0) >= 3 && (s.dry||0) >= 3 && (s.advanced||0) >= 2; },
    score: function(s){ return (s.large||0)+(s.dry||0)+(s.advanced||0)+(s.charisma||0); }
  },
  { name: 'アルダブラゾウガメ', latin: 'Aldabrachelys gigantea', emoji: '🐘', difficulty: '上級', size: 'XL（80〜120cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: 'セイシェル・アルダブラ島固有の巨大リクガメ。個人飼育は法的に可能だが広大なスペースと数十年の覚悟が必要。ケヅメより穏やかな性格で知られる。',
    specs: { '最大甲長': '120cm超', '主な食事': '野草・乾草', '水容量': '水浴び池必須', '温度': '28〜33℃' },
    coreSpecs: { size: '120cm超', temp: '28〜33℃', lifespan: '80〜150年', diet: '草食（野草・野菜中心）' },
    extraSpecs: {},
    links: [{ label: '乾燥系リクガメ 飼育ガイド', href: '../guide-dry.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.large||0) >= 3 && (s.humid||0) >= 1 && (s.advanced||0) >= 3; },
    score: function(s){ return (s.large||0)+(s.humid||0)+(s.advanced||0)+(s.charisma||0); }
  },
  { name: 'インプレッサムツアシガメ', latin: 'Manouria impressa', emoji: '🏔️', difficulty: '上級', size: 'M（25〜31cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: 'リクガメ科で最も飼育が難しいとされるアジア産ムツアシガメ属。高標高の多湿林産で低温・高湿度・通気の三立が必要。長期飼育記録が少なく専門家でも難しい究極の挑戦種。',
    specs: { '最大甲長': '31cm', '主な食事': 'キノコ・果物・野草', '水容量': '水浴び場必須', '温度': '18〜24℃' },
    coreSpecs: { size: '31cm', temp: '18〜24℃', lifespan: '30〜80年', diet: '草食（野草・野菜中心）' },
    extraSpecs: {},
    links: [{ label: '多湿系リクガメ 飼育ガイド', href: '../guide-arid.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.large||0) >= 2 && (s.humid||0) >= 2 && (s.advanced||0) >= 3; },
    score: function(s){ return (s.large||0)+(s.humid||0)+(s.advanced||0)+(s.asia_land||0); }
  },
  { name: 'パンケーキリクガメ', latin: 'Malacochersus tornieri', emoji: '🫓', difficulty: '上級', size: 'S（14〜18cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '甲羅が薄く平たいリクガメ。岩の隙間に逃げ込む独特の習性を持ち、他のリクガメとは全く異なる生態が面白い。タンザニア・ケニア原産。通気性の良い岩場環境が必要。CITES II。国内流通は希少。',
    specs: { '最大甲長': '18cm', '主な食事': '野草・乾草', '水容量': '浅め水入れ', '温度': '25〜34℃' },
    coreSpecs: { size: '18cm', temp: '25〜34℃', lifespan: '20〜30年', diet: '草食（野草・乾草中心）' },
    extraSpecs: {},
    links: [{ label: '乾燥系リクガメ 飼育ガイド', href: '../guide-dry.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.compact||0) >= 2 && (s.dry||0) >= 2 && (s.advanced||0) >= 1; },
    score: function(s){ return (s.compact||0)+(s.dry||0)+(s.advanced||0)+(s.collector||0)+(s.ultra_rare||0)+(s.charisma||0); }
  },
  { name: 'インドホシガメ', latin: 'Geochelone elegans', emoji: '⭐', difficulty: '上級', size: 'M（20〜30cm）', cites: 'CITES I', legal: 'cites_i',
    reason: '放射状の美しい模様が宝石のように輝くリクガメ。インド・パキスタン・スリランカ原産。CITES I・商業取引禁止。現在流通する個体は国内CBのみで、乾燥と温度管理の高い技術が必要。',
    specs: { '最大甲長': '30cm', '主な食事': '野草・野菜・乾草', '水容量': '浅め水入れ', '温度': '26〜35℃' },
    coreSpecs: { size: '30cm', temp: '26〜35℃', lifespan: '30〜50年', diet: '草食（野草・野菜・乾草）' },
    extraSpecs: {},
    links: [{ label: '乾燥系リクガメ 飼育ガイド', href: '../guide-dry.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.dry||0) >= 2 && (s.advanced||0) >= 2 && (s.charisma||0) >= 2; },
    score: function(s){ return (s.dry||0)+(s.advanced||0)+(s.charisma||0)*2+(s.collector||0)+(s.herbivore||0)+(s.tropical_climate||0); }
  },
  { name: 'ビルマホシガメ', latin: 'Geochelone platynota', emoji: '🌟', difficulty: '上級', size: 'M（28〜35cm）', cites: 'CITES I', legal: 'cites_i',
    reason: 'ミャンマー固有のホシガメ。インドホシガメより扁平で大型になる幻の種。CITES I・商業取引禁止で国内流通はごく稀。飼育記録を持つことが保全に貢献する意義深い稀少種。',
    specs: { '最大甲長': '35cm', '主な食事': '野草・野菜', '水容量': '浅め水入れ', '温度': '26〜34℃' },
    coreSpecs: { size: '35cm', temp: '26〜34℃', lifespan: '40〜60年', diet: '草食（野草・野菜）' },
    extraSpecs: {},
    links: [{ label: '乾燥系リクガメ 飼育ガイド', href: '../guide-dry.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.dry||0) >= 2 && (s.advanced||0) >= 3 && (s.expert||0) >= 1; },
    score: function(s){ return (s.dry||0)+(s.advanced||0)+(s.charisma||0)+(s.expert||0)+(s.ultra_rare||0)*2+(s.collector||0); }
  },
  { name: 'エジプトリクガメ', latin: 'Testudo kleinmanni', emoji: '🏺', difficulty: '上級', size: 'S（10〜13cm）', cites: 'CITES I', legal: 'cites_i',
    reason: '世界最小クラスのリクガメで砂漠・半乾燥地帯に生息。エジプト・リビア原産。CITES I・商業取引禁止で国内流通はほぼなし。極度の乾燥と高温管理が必要な超上級者向けの希少種。',
    specs: { '最大甲長': '13cm', '主な食事': '野草・乾草', '水容量': '極少量', '温度': '28〜38℃' },
    coreSpecs: { size: '13cm', temp: '28〜38℃', lifespan: '20〜40年', diet: '草食（乾草・砂漠植物）' },
    extraSpecs: {},
    links: [{ label: '乾燥系リクガメ 飼育ガイド', href: '../guide-dry.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.compact||0) >= 3 && (s.dry||0) >= 3 && (s.advanced||0) >= 3; },
    score: function(s){ return (s.compact||0)+(s.dry||0)+(s.advanced||0)+(s.expert||0)+(s.ultra_rare||0)*2+(s.collector||0)+(s.small_form||0); }
  },
  { name: 'ソリガメ', latin: 'Chersina angulata', emoji: '🔱', difficulty: '上級', size: 'M（15〜25cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '南アフリカ・ケープ地方原産のリクガメ。甲羅前端が反り上がった独特の形状が名前の由来。乾燥した低木地帯に生息し、高温・乾燥・通気性の良い環境が必要。国内流通は少なく希少。CITES II。',
    specs: { '最大甲長': '25cm', '主な食事': '野草・野菜', '水容量': '浅め水入れ', '温度': '25〜35℃' },
    coreSpecs: { size: '25cm', temp: '25〜35℃', lifespan: '20〜40年', diet: '草食（野草・多肉植物）' },
    extraSpecs: {},
    links: [{ label: '乾燥系リクガメ 飼育ガイド', href: '../guide-dry.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.compact||0) >= 2 && (s.dry||0) >= 2 && (s.advanced||0) >= 2; },
    score: function(s){ return (s.compact||0)+(s.dry||0)+(s.advanced||0)+(s.charisma||0)+(s.collector||0)+(s.ultra_rare||0); }
  },
  { name: 'セオレガメ（ホメアナ）', latin: 'Kinixys homeana', emoji: '🔒', difficulty: '上級', size: 'M（18〜25cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '西アフリカの熱帯雨林に生息するセオレガメ。甲羅後半がヒンジで閉じる独特の機構を持つ。高湿度・高温の環境が必要で、WC個体はストレスや寄生虫に弱い。CB個体推奨の難種。CITES II。',
    specs: { '最大甲長': '25cm', '主な食事': 'キノコ・果実・ミミズ', '水容量': '浅め水入れ', '温度': '26〜32℃' },
    coreSpecs: { size: '25cm', temp: '26〜32℃', lifespan: '20〜40年', diet: '雑食（キノコ・果実・小動物）' },
    extraSpecs: {},
    links: [{ label: '多湿系リクガメ 飼育ガイド', href: '../guide-moist.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.humid||0) >= 2 && (s.advanced||0) >= 2 && (s.tropical_climate||0) >= 1; },
    score: function(s){ return (s.humid||0)+(s.advanced||0)+(s.tropical_climate||0)+(s.charisma||0)+(s.collector||0)+(s.expert||0); }
  },
  { name: 'マダガスカルクモノスガメ', latin: 'Pyxis arachnoides', emoji: '🕸️', difficulty: '上級', size: 'S（12〜15cm）', cites: 'CITES I', legal: 'cites_i',
    reason: 'マダガスカル固有の超希少リクガメ。甲羅に蜘蛛の巣のような放射状模様が入る。CITES I・商業取引禁止で世界的にも飼育記録が少ない。乾燥と季節変化（乾季・雨季）の再現が飼育の鍵。',
    specs: { '最大甲長': '15cm', '主な食事': '野草・乾草', '水容量': '極少量〜なし（乾季）', '温度': '25〜35℃' },
    coreSpecs: { size: '15cm', temp: '25〜35℃', lifespan: '20〜40年', diet: '草食（乾草・砂漠植物）' },
    extraSpecs: {},
    links: [{ label: '乾燥系リクガメ 飼育ガイド', href: '../guide-dry.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.compact||0) >= 2 && (s.dry||0) >= 3 && (s.expert||0) >= 1; },
    score: function(s){ return (s.compact||0)+(s.dry||0)+(s.expert||0)+(s.ultra_rare||0)*3+(s.collector||0)+(s.charisma||0)+(s.small_form||0); }
  }
],

// ==================== 水棲ガメルート ====================
aquatic: [
  { name: 'ニオイガメ', latin: 'Sternotherus odoratus', emoji: '🔬', difficulty: '入門', size: 'S（10〜14cm）', cites: null, legal: null,
    reason: '水棲ガメ入門の定番。最大14cm程度で30〜45cm水槽から飼育可能。威嚇時に臭いを出しますが慣れればほぼ無臭。お手頃価格で流通も安定。',
    specs: { '最大甲長': '14cm', '水槽サイズ': '30cm〜', '水温': '22〜28℃', '難易度': '★☆☆' },
    coreSpecs: { size: '14cm', temp: '22〜28℃', lifespan: '20〜50年', diet: '雑食' },
    extraSpecs: { tankSize: '30cm〜' },
    links: [{ label: '半水棲ガメ 飼育ガイド', href: '../guide-semi.html' }], asin: null,
    slug: 'musk-turtle', hasPage: true,
    match: function(s){ return (s.small_tank||0) >= 2 && (s.beginner||0) >= 2; },
    score: function(s){ return (s.small_tank||0)+(s.beginner||0)+(s.observational||0)+(s.mainstream||0)+(s.mud_lover||0)+(s.na_water||0)+(s.cool_climate||0); }
  },
  { name: 'ヒメニオイガメ', latin: 'Sternotherus depressus', emoji: '🔭', difficulty: '入門', size: 'S（8〜11cm）', cites: 'CITES II', legal: null,
    reason: '国内流通する最小クラスの水棲ガメ。扁平な体型が特徴でニオイガメより更に小さく、30cm水槽から飼育可能。穏やかで飼いやすい。',
    specs: { '最大甲長': '11cm', '水槽サイズ': '30cm〜', '水温': '20〜27℃', '難易度': '★☆☆' },
    coreSpecs: { size: '11cm', temp: '20〜27℃', lifespan: '15〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '30cm〜' },
    links: [{ label: '半水棲ガメ 飼育ガイド', href: '../guide-semi.html' }], asin: null,
    slug: 'hime-nioi-turtle', hasPage: true,
    match: function(s){ return (s.small_tank||0) >= 3 && (s.observational||0) >= 1; },
    score: function(s){ return (s.small_tank||0)+(s.beginner||0)+(s.observational||0)+(s.na_water||0)+(s.cool_climate||0); }
  },
  { name: 'ミシシッピドロガメ', latin: 'Kinosternon subrubrum hippocrepis', emoji: '🌿', difficulty: '入門', size: 'S（10〜12cm）', cites: null, legal: null,
    reason: '10cm程度の超小型種。陸上に上がる習性があるためシェルターと陸場の確保が必要。ニオイガメより温和な個体が多い。',
    specs: { '最大甲長': '12cm', '水槽サイズ': '30cm〜', '水温': '20〜26℃', '難易度': '★☆☆' },
    coreSpecs: { size: '12cm', temp: '20〜26℃', lifespan: '15〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '30cm〜' },
    links: [{ label: '半水棲ガメ 飼育ガイド', href: '../guide-semi.html' }], asin: null,
    slug: 'mississippi-mud-turtle', hasPage: true,
    match: function(s){ return (s.small_tank||0) >= 2 && (s.beginner||0) >= 1; },
    score: function(s){ return (s.small_tank||0)+(s.beginner||0)+(s.observational||0)+(s.mainstream||0)+(s.mud_lover||0)+(s.na_water||0)+(s.warm_climate||0); }
  },
  { name: 'ミスジドロガメ', latin: 'Kinosternon baurii', emoji: '〰️', difficulty: '入門〜中級', size: 'S（9〜12cm）', cites: null, legal: null,
    reason: '甲羅に3本の明瞭な筋が走る美しいドロガメ。小型で飼育しやすく温和な性格。ニオイガメと並ぶ小型水棲ガメ入門の選択肢。',
    specs: { '最大甲長': '12cm', '水槽サイズ': '30cm〜', '水温': '20〜27℃', '難易度': '★☆☆' },
    coreSpecs: { size: '12cm', temp: '20〜27℃', lifespan: '15〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '30cm〜' },
    links: [{ label: '半水棲ガメ 飼育ガイド', href: '../guide-semi.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.small_tank||0) >= 2 && (s.beginner||0) >= 1; },
    score: function(s){ return (s.small_tank||0)+(s.beginner||0)+(s.observational||0)+(s.mud_lover||0)+(s.na_water||0)+(s.warm_climate||0); }
  },
  { name: 'カブトニオイガメ', latin: 'Sternotherus carinatus', emoji: '⛑️', difficulty: '入門〜中級', size: 'M（10〜15cm）', cites: null, legal: null,
    reason: 'キールが目立つ個性的な甲羅が魅力。ニオイガメよりやや大型化しますが45cm水槽から飼育可能。気性がやや荒い個体もいます。',
    specs: { '最大甲長': '15cm', '水槽サイズ': '45cm〜', '水温': '22〜28℃', '難易度': '★☆☆' },
    coreSpecs: { size: '15cm', temp: '22〜28℃', lifespan: '15〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '45cm〜' },
    links: [{ label: '半水棲ガメ 飼育ガイド', href: '../guide-semi.html' }], asin: null,
    slug: 'razorback-musk-turtle', hasPage: true,
    match: function(s){ return (s.small_tank||0) >= 1 && (s.observational||0) >= 2; },
    score: function(s){ return (s.small_tank||0)+(s.beginner||0)+(s.observational||0)+(s.mud_lover||0)+(s.na_water||0)+(s.warm_climate||0); }
  },
  { name: 'スジクビニオイガメ', latin: 'Sternotherus minor peltifer', emoji: '🎗️', difficulty: '中級', size: 'S（8〜11cm）', cites: null, legal: null,
    reason: '首と頭部に細かいストライプが走る美しいニオイガメ系の小型種。国内CB流通が確認されており、マニアに人気。小型水槽で観察を楽しめる。',
    specs: { '最大甲長': '11cm', '水槽サイズ': '30cm〜', '水温': '20〜27℃', '難易度': '★★☆' },
    coreSpecs: { size: '11cm', temp: '20〜27℃', lifespan: '15〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '30cm〜' },
    links: [{ label: '半水棲ガメ 飼育ガイド', href: '../guide-semi.html' }], asin: null,
    slug: 'stripe-necked-musk-turtle', hasPage: true,
    match: function(s){ return (s.small_tank||0) >= 2 && (s.observational||0) >= 2 && (s.intermediate||0) >= 2; },
    score: function(s){ return (s.small_tank||0)+(s.observational||0)+(s.intermediate||0)+(s.rare_water||0)+(s.mud_lover||0)+(s.na_water||0)+(s.warm_climate||0); }
  },
  { name: 'ホオアカドロガメ', latin: 'Kinosternon cruentatum', emoji: '🔴', difficulty: '中級', size: 'M（13〜15cm）', cites: null, legal: null,
    reason: '頬の赤みが特徴的なメキシコ〜中米産のドロガメ。温和な性格で45cm水槽から飼育可能。国内CB流通が増加しており入手しやすくなっている。',
    specs: { '最大甲長': '15cm', '水槽サイズ': '45cm〜', '水温': '24〜29℃', '難易度': '★★☆' },
    coreSpecs: { size: '15cm', temp: '24〜29℃', lifespan: '15〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '45cm〜' },
    links: [{ label: '半水棲ガメ 飼育ガイド', href: '../guide-semi.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.small_tank||0) >= 1 && (s.intermediate||0) >= 1; },
    score: function(s){ return (s.small_tank||0)+(s.maintenance||0)+(s.intermediate||0)+(s.mud_lover||0)+(s.na_water||0)+(s.tropical_climate||0); }
  },
  { name: 'ペインテッドタートル', latin: 'Chrysemys picta', emoji: '🎨', difficulty: '入門', size: 'M（13〜25cm）', cites: null, legal: null,
    reason: '甲羅の縁に赤・黄のラインが走る美しい種。泳ぎが活発で60〜90cm水槽が適切。草食傾向が強く管理しやすい。',
    specs: { '最大甲長': '25cm（メス）', '水槽サイズ': '60cm〜', '水温': '20〜28℃', '難易度': '★☆☆' },
    coreSpecs: { size: '25cm（メス）', temp: '20〜28℃', lifespan: '15〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '60cm〜' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: 'painted-turtle', hasPage: true,
    match: function(s){ return (s.medium_tank||0) >= 2 && (s.active||0) >= 2; },
    score: function(s){ return (s.medium_tank||0)+(s.active||0)+(s.beginner||0)+(s.mainstream||0)*2+(s.swimmer||0)+(s.na_water||0)+(s.cool_climate||0); }
  },
  { name: 'クサガメ', latin: 'Mauremys reevesii', emoji: '🇯🇵', difficulty: '入門', size: 'M（15〜25cm）', cites: null, legal: null,
    reason: '昔からペットとして親しまれてきたガメ。丈夫で適応力が高く初心者にも飼いやすい。外来起源説があるため野外への放流は厳禁。国内CB個体を選ぶこと。',
    specs: { '最大甲長': '25cm', '水槽サイズ': '60cm〜', '水温': '20〜28℃', '難易度': '★☆☆' },
    coreSpecs: { size: '25cm', temp: '20〜28℃', lifespan: '20〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '60cm〜' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: 'reeves-turtle', hasPage: true,
    match: function(s){ return (s.medium_tank||0) >= 1 && (s.beginner||0) >= 2; },
    score: function(s){ return (s.medium_tank||0)+(s.beginner||0)+(s.active||0)+(s.mainstream||0)+(s.bottom_dweller||0)+(s.asia_water||0)+(s.cool_climate||0); }
  },
  { name: 'キバラガメ', latin: 'Trachemys scripta scripta', emoji: '💛', difficulty: '入門', size: 'M（17〜27cm）', cites: null, legal: null,
    reason: 'アカミミガメの近縁種で耳が黄色い。泳ぎが活発で観察が楽しい。アカミミガメと違い特定外来生物ではなく新規購入・飼育が可能。',
    specs: { '最大甲長': '27cm', '水槽サイズ': '60cm〜', '水温': '22〜28℃', '難易度': '★☆☆' },
    coreSpecs: { size: '27cm', temp: '22〜28℃', lifespan: '20〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '60cm〜' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: 'yellow-bellied-slider', hasPage: true,
    match: function(s){ return (s.medium_tank||0) >= 1 && (s.active||0) >= 2; },
    score: function(s){ return (s.medium_tank||0)+(s.active||0)+(s.beginner||0)+(s.mainstream||0)+(s.swimmer||0)+(s.na_water||0)+(s.warm_climate||0); }
  },
  { name: 'ミシシッピアカミミガメ', latin: 'Trachemys scripta elegans', emoji: '🔴', difficulty: '入門', size: 'L（20〜30cm）', cites: null, legal: 'conditional_invasive',
    reason: '【条件付特定外来生物】新規購入・販売は禁止ですが、既に飼育中の場合は継続飼育・少数無償譲渡が可能。野外への放流は厳禁。責任ある飼育が求められます。',
    specs: { '最大甲長': '30cm', '水槽サイズ': '90cm〜', '水温': '22〜28℃', '難易度': '★☆☆' },
    coreSpecs: { size: '30cm', temp: '22〜28℃', lifespan: '30〜40年', diet: '雑食' },
    extraSpecs: { tankSize: '90cm〜' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.large_tank||0) >= 1 && (s.beginner||0) >= 2 && (s.active||0) >= 2; },
    score: function(s){ return (s.large_tank||0)+(s.active||0)+(s.beginner||0)+(s.swimmer||0)+(s.na_water||0)+(s.warm_climate||0); }
  },
  { name: 'ミシシッピチズガメ', latin: 'Graptemys pseudogeographica kohni', emoji: '🗺️', difficulty: '中級', size: 'M（オス10cm/メス20cm）', cites: null, legal: null,
    reason: 'チズガメ類で最も流通が多い入門種。独特の甲羅のキールと首の模様が美しい。水質に敏感なのでフィルターは必須。',
    specs: { '最大甲長': '20cm（メス）', '水槽サイズ': '60cm〜', '水温': '22〜28℃', '難易度': '★★☆' },
    coreSpecs: { size: '20cm（メス）', temp: '22〜28℃', lifespan: '15〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '60cm〜' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: 'mississippi-map-turtle', hasPage: true,
    match: function(s){ return (s.medium_tank||0) >= 2 && (s.maintenance||0) >= 2; },
    score: function(s){ return (s.medium_tank||0)+(s.maintenance||0)+(s.observational||0)+(s.beauty||0)+(s.bottom_dweller||0)+(s.na_water||0)+(s.warm_climate||0); }
  },
  { name: 'ニセチズガメ', latin: 'Graptemys pseudogeographica pseudogeographica', emoji: '🗺️', difficulty: '中級', size: 'M（オス12cm/メス22cm）', cites: null, legal: null,
    reason: 'ミシシッピチズガメの基亜種。背中のキールがより目立ち観察の楽しさがある。チズガメを一通り揃えたい中級者向け。',
    specs: { '最大甲長': '22cm（メス）', '水槽サイズ': '60cm〜', '水温': '22〜28℃', '難易度': '★★☆' },
    coreSpecs: { size: '22cm（メス）', temp: '22〜28℃', lifespan: '15〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '60cm〜' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: 'false-map-turtle', hasPage: true,
    match: function(s){ return (s.medium_tank||0) >= 2 && (s.maintenance||0) >= 1 && (s.intermediate||0) >= 1; },
    score: function(s){ return (s.medium_tank||0)+(s.maintenance||0)+(s.observational||0)+(s.beauty||0)+(s.bottom_dweller||0)+(s.na_water||0)+(s.warm_climate||0); }
  },
  { name: 'フトマユチズガメ', latin: 'Graptemys ouachitensis', emoji: '🎭', difficulty: '中級', size: 'M（オス12cm/メス20cm）', cites: null, legal: null,
    reason: '目の後方に特徴的な眉のような模様がある美しいチズガメ。チズガメ類の中で最も気性が穏やかとも言われる。中級者が2種目として選ぶのにも最適。',
    specs: { '最大甲長': '20cm（メス）', '水槽サイズ': '60cm〜', '水温': '22〜28℃', '難易度': '★★☆' },
    coreSpecs: { size: '20cm（メス）', temp: '22〜28℃', lifespan: '15〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '60cm〜' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.medium_tank||0) >= 2 && (s.maintenance||0) >= 2 && (s.intermediate||0) >= 1; },
    score: function(s){ return (s.medium_tank||0)+(s.maintenance||0)+(s.observational||0)+(s.intermediate||0)+(s.beauty||0)+(s.bottom_dweller||0)+(s.na_water||0)+(s.warm_climate||0); }
  },
  { name: 'ニホンイシガメ', latin: 'Mauremys japonica', emoji: '🌸', difficulty: '中級', size: 'M（13〜20cm）', cites: null, legal: null,
    reason: '日本固有種で国内CBの流通も確立。温帯産で夏の高温管理が重要。クサガメより清水を好む傾向がある。',
    specs: { '最大甲長': '20cm', '水槽サイズ': '60cm〜', '水温': '18〜27℃', '難易度': '★★☆' },
    coreSpecs: { size: '20cm', temp: '18〜27℃', lifespan: '20〜40年', diet: '雑食' },
    extraSpecs: { tankSize: '60cm〜' },
    links: [{ label: '日本産カメ 飼育ガイド', href: '../guide-japan.html' }], asin: null,
    slug: 'japanese-pond-turtle', hasPage: true,
    match: function(s){ return (s.medium_tank||0) >= 1 && (s.intermediate||0) >= 1; },
    score: function(s){ return (s.medium_tank||0)+(s.maintenance||0)+(s.observational||0)+(s.intermediate||0)+(s.japan_native||0)+(s.bottom_dweller||0)+(s.asia_water||0)+(s.cool_climate||0); }
  },
  { name: 'ヤエヤマイシガメ', latin: 'Mauremys mutica kami', emoji: '🌺', difficulty: '中級', size: 'M（15〜20cm）', cites: null, legal: null,
    reason: '台湾・中国南部および八重山諸島に分布するイシガメの亜種。宮古島では国内外来種として問題視されており飼育個体の野外放流は厳禁。国内CB入手推奨。',
    specs: { '最大甲長': '20cm', '水槽サイズ': '60cm〜', '水温': '20〜28℃', '難易度': '★★☆' },
    coreSpecs: { size: '20cm', temp: '20〜28℃', lifespan: '15〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '60cm〜' },
    links: [{ label: '日本産カメ 飼育ガイド', href: '../guide-japan.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.medium_tank||0) >= 1 && (s.intermediate||0) >= 2; },
    score: function(s){ return (s.medium_tank||0)+(s.maintenance||0)+(s.intermediate||0)+(s.observational||0)+(s.japan_native||0)+(s.bottom_dweller||0)+(s.asia_water||0)+(s.warm_climate||0); }
  },
  { name: 'ミナミイシガメ', latin: 'Mauremys mutica', emoji: '🍃', difficulty: '中級', size: 'M（15〜20cm）', cites: null, legal: null,
    reason: '台湾・中国南部産のイシガメ属。国内CB流通あり。ニホンイシガメよりやや高温を好む傾向。コンパクトで管理しやすい。',
    specs: { '最大甲長': '20cm', '水槽サイズ': '60cm〜', '水温': '22〜29℃', '難易度': '★★☆' },
    coreSpecs: { size: '20cm', temp: '22〜29℃', lifespan: '15〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '60cm〜' },
    links: [{ label: '日本産カメ 飼育ガイド', href: '../guide-japan.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.medium_tank||0) >= 1 && (s.intermediate||0) >= 1 && (s.maintenance||0) >= 1; },
    score: function(s){ return (s.medium_tank||0)+(s.maintenance||0)+(s.intermediate||0)+(s.japan_native||0)+(s.bottom_dweller||0)+(s.asia_water||0)+(s.warm_climate||0); }
  },
  { name: 'ニシキマゲクビガメ（ピンクベリー）', latin: 'Emydura subglobosa', emoji: '🌸', difficulty: '中〜上級', size: 'M（18〜25cm）', cites: null, legal: null,
    reason: '腹甲がピンク色の美しい曲頸類。横に首を曲げて引っ込める独特の動作が魅力。曲頸類入門として人気が高い。',
    specs: { '最大甲長': '25cm', '水槽サイズ': '60cm〜', '水温': '24〜29℃', '難易度': '★★☆' },
    coreSpecs: { size: '25cm', temp: '24〜29℃', lifespan: '15〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '60cm〜' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: 'pink-bellied-side-necked-turtle', hasPage: true,
    match: function(s){ return (s.medium_tank||0) >= 2 && (s.observational||0) >= 2; },
    score: function(s){ return (s.medium_tank||0)+(s.observational||0)+(s.intermediate||0)+(s.bottom_dweller||0)+(s.sa_water||0)+(s.tropical_climate||0); }
  },
  { name: 'ペニンシュラクーター', latin: 'Pseudemys peninsularis', emoji: '🏊', difficulty: '中級', size: 'L（25〜37cm）', cites: null, legal: null,
    reason: 'フロリダ半島産の大型スライダー系。活発な泳ぎと草食傾向で90cm以上の水槽が必要。大きくなる種を飼いたい中級者向け。',
    specs: { '最大甲長': '37cm（メス）', '水槽サイズ': '90cm〜', '水温': '22〜28℃', '難易度': '★★☆' },
    coreSpecs: { size: '37cm（メス）', temp: '22〜28℃', lifespan: '15〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '90cm〜' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.large_tank||0) >= 2 && (s.active||0) >= 2; },
    score: function(s){ return (s.large_tank||0)+(s.active||0)+(s.intermediate||0)+(s.swimmer||0)+(s.na_water||0)+(s.warm_climate||0); }
  },
  { name: 'ブランディングガメ', latin: 'Emydoidea blandingii', emoji: '😊', difficulty: '上級', size: 'M（17〜27cm）', cites: 'CITES II', legal: null,
    reason: '黄色い喉元と半開きの口がにっこり笑っているように見える独特の風貌。温帯種で夏の高温に弱く保冷が必要。国内CB確認済み。',
    specs: { '最大甲長': '27cm', '水槽サイズ': '60cm〜', '水温': '15〜24℃', '難易度': '★★★' },
    coreSpecs: { size: '27cm', temp: '15〜24℃', lifespan: '15〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '60cm〜' },
    links: [{ label: '半水棲ガメ 飼育ガイド', href: '../guide-semi.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.medium_tank||0) >= 1 && (s.advanced||0) >= 2; },
    score: function(s){ return (s.medium_tank||0)+(s.advanced||0)+(s.observational||0)+(s.na_water||0)+(s.cool_climate||0); }
  },
  { name: 'マタマタ', latin: 'Chelus fimbriata', emoji: '🍂', difficulty: '上級', size: 'L（35〜45cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '枯れ葉のような外見で待ち伏せして魚を丸ごと吸い込む神秘的な種。水流を嫌い独特の飼育法を習得する必要がある本格派種。',
    specs: { '最大甲長': '45cm', '水槽サイズ': '90cm〜', '水温': '26〜30℃', '難易度': '★★★' },
    coreSpecs: { size: '45cm', temp: '26〜30℃', lifespan: '15〜25年', diet: '肉食（待ち伏せ捕食）' },
    extraSpecs: { tankSize: '90cm〜' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: 'matamata', hasPage: true,
    match: function(s){ return (s.large_tank||0) >= 2 && (s.ambush||0) >= 2; },
    score: function(s){ return (s.ambush||0)+(s.advanced||0)+(s.large_tank||0)+(s.sa_water||0)+(s.tropical_climate||0); }
  },
  { name: 'サラドロガメ', latin: 'Kinosternon integrum', emoji: '🟤', difficulty: '中級', size: 'M（15〜20cm）', cites: null, legal: null,
    reason: 'メキシコ固有のドロガメ。甲長20cm程度と国内流通するドロガメ属では大型。温和な性格で60cm水槽から飼育できる。国内CB流通が増加中。',
    specs: { '最大甲長': '20cm', '水槽サイズ': '60cm〜', '水温': '24〜29℃', '難易度': '★★☆' },
    coreSpecs: { size: '20cm', temp: '24〜29℃', lifespan: '15〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '60cm〜' },
    links: [{ label: '半水棲ガメ 飼育ガイド', href: '../guide-semi.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.medium_tank||0) >= 1 && (s.intermediate||0) >= 1; },
    score: function(s){ return (s.medium_tank||0)+(s.intermediate||0)+(s.maintenance||0)+(s.rare_water||0)+(s.mud_lover||0)+(s.na_water||0)+(s.tropical_climate||0); }
  },
  { name: 'ヨーロッパヌマガメ', latin: 'Emys orbicularis', emoji: '🌿', difficulty: '中級', size: 'M（15〜20cm）', cites: null, legal: null,
    reason: 'ユーラシア大陸唯一のヌマガメ科。国内CB・EUCB流通あり。低温に強く日本の温帯気候にも馴染みやすい。甲羅と頭部の黄色い斑点が美しい。',
    specs: { '最大甲長': '20cm', '水槽サイズ': '60cm〜', '水温': '16〜26℃', '難易度': '★★☆' },
    coreSpecs: { size: '20cm', temp: '16〜26℃', lifespan: '15〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '60cm〜' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.medium_tank||0) >= 1 && (s.intermediate||0) >= 1; },
    score: function(s){ return (s.medium_tank||0)+(s.intermediate||0)+(s.observational||0)+(s.eu_water||0)+(s.cool_climate||0); }
  },
  { name: 'カントンクサガメ', latin: 'Mauremys reevesii（広東型）', emoji: '🟡', difficulty: '入門〜中級', size: 'M（15〜25cm）', cites: null, legal: null,
    reason: 'クサガメの広東産地個体群。黄みがかった体色や明確な産地証明が魅力。ぶりくら等で国内CB流通確認済み。野外への放流は厳禁。',
    specs: { '最大甲長': '25cm', '水槽サイズ': '60cm〜', '水温': '20〜28℃', '難易度': '★☆☆' },
    coreSpecs: { size: '25cm', temp: '20〜28℃', lifespan: '15〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '60cm〜' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: 'canton-reeves-turtle', hasPage: true,
    match: function(s){ return (s.medium_tank||0) >= 1 && (s.beginner||0) >= 1; },
    score: function(s){ return (s.medium_tank||0)+(s.beginner||0)+(s.active||0)+(s.mainstream||0)+(s.japan_native||0)+(s.bottom_dweller||0)+(s.asia_water||0)+(s.warm_climate||0); }
  },
  { name: 'キイロドロガメ', latin: 'Kinosternon flavescens', emoji: '💛', difficulty: '中級', size: 'M（10〜14cm）', cites: null, legal: null,
    reason: '腹甲が黄みがかる個性的なドロガメ。テキサス〜イリノイ産。小型で管理しやすく、ドロガメ系コレクションの1種として人気。流通確認済み。',
    specs: { '最大甲長': '14cm', '水槽サイズ': '30cm〜', '水温': '20〜27℃', '難易度': '★★☆' },
    coreSpecs: { size: '14cm', temp: '20〜27℃', lifespan: '15〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '30cm〜' },
    links: [{ label: '半水棲ガメ 飼育ガイド', href: '../guide-semi.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.small_tank||0) >= 2 && (s.intermediate||0) >= 1; },
    score: function(s){ return (s.small_tank||0)+(s.intermediate||0)+(s.observational||0)+(s.rare_water||0)+(s.mud_lover||0)+(s.na_water||0)+(s.warm_climate||0); }
  },
  { name: 'ハーレラドロガメ', latin: 'Kinosternon herrerai', emoji: '🔸', difficulty: '上級', size: 'M（14〜16cm）', cites: null, legal: null,
    reason: 'メキシコ・ベラクルス州に限定分布する希少なドロガメ。ザラアシドロガメとは別種。専門店からのCB入荷が確認されており、希少ドロガメを集めるマニア向き。',
    specs: { '最大甲長': '16cm', '水槽サイズ': '45cm〜', '水温': '24〜29℃', '難易度': '★★★' },
    coreSpecs: { size: '16cm', temp: '24〜29℃', lifespan: '15〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '45cm〜' },
    links: [{ label: '半水棲ガメ 飼育ガイド', href: '../guide-semi.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.small_tank||0) >= 1 && (s.advanced||0) >= 2; },
    score: function(s){ return (s.small_tank||0)+(s.advanced||0)+(s.observational||0)+(s.rare_water||0)+(s.mud_lover||0)+(s.na_water||0)+(s.tropical_climate||0); }
  },
  { name: 'シロクチドロガメ', latin: 'Kinosternon leucostomum', emoji: '⬜', difficulty: '上級', size: 'M（15〜17cm）', cites: null, legal: null,
    reason: '白い口周りが特徴の中米産ドロガメ。ぶりくらでCB出品確認済み。ドロガメ属の中でも比較的大型で存在感がある。上級者の希少種コレクション向き。',
    specs: { '最大甲長': '17cm', '水槽サイズ': '60cm〜', '水温': '24〜30℃', '難易度': '★★★' },
    coreSpecs: { size: '17cm', temp: '24〜30℃', lifespan: '15〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '60cm〜' },
    links: [{ label: '半水棲ガメ 飼育ガイド', href: '../guide-semi.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.small_tank||0) >= 1 && (s.advanced||0) >= 2 && (s.maintenance||0) >= 1; },
    score: function(s){ return (s.small_tank||0)+(s.advanced||0)+(s.observational||0)+(s.rare_water||0)+(s.mud_lover||0)+(s.na_water||0)+(s.tropical_climate||0); }
  },
  { name: 'クロコブチズガメ', latin: 'Graptemys nigrinoda', emoji: '⚫', difficulty: '中〜上級', size: 'M（オス10cm/メス18cm）', cites: null, legal: null,
    reason: '背中キールの黒いコブが印象的なチズガメ。ぶりくらCB出品確認済み。チズガメ属の中でも個性的な外見で、コレクション性が高い中上級種。',
    specs: { '最大甲長': '18cm（メス）', '水槽サイズ': '60cm〜', '水温': '22〜28℃', '難易度': '★★☆' },
    coreSpecs: { size: '18cm（メス）', temp: '22〜28℃', lifespan: '15〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '60cm〜' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.medium_tank||0) >= 2 && (s.maintenance||0) >= 2 && (s.advanced||0) >= 1; },
    score: function(s){ return (s.medium_tank||0)+(s.maintenance||0)+(s.advanced||0)+(s.observational||0)+(s.beauty||0)+(s.bottom_dweller||0)+(s.na_water||0)+(s.warm_climate||0); }
  },
  { name: 'ワモンチズガメ', latin: 'Graptemys oculifera', emoji: '🔵', difficulty: '上級', size: 'M（オス9cm/メス18cm）', cites: null, legal: null,
    reason: '目の後方に輪状の美麗模様が入るチズガメ屈指の美種。ぶりくら2025出品リスト記載。水質への敏感さと飼育難度から上級者向きだが所有する価値は高い。',
    specs: { '最大甲長': '18cm（メス）', '水槽サイズ': '60cm〜', '水温': '22〜28℃', '難易度': '★★★' },
    coreSpecs: { size: '18cm（メス）', temp: '22〜28℃', lifespan: '15〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '60cm〜' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.medium_tank||0) >= 2 && (s.maintenance||0) >= 3 && (s.advanced||0) >= 3; },
    score: function(s){ return (s.medium_tank||0)+(s.maintenance||0)+(s.advanced||0)+(s.observational||0)+(s.beauty||0)+(s.bottom_dweller||0)+(s.na_water||0)+(s.warm_climate||0); }
  },
  { name: 'オウアチタチズガメ', latin: 'Graptemys ouachitensis', emoji: '🗺️', difficulty: '中級', size: 'M（オス10cm/メス22cm）', cites: null, legal: null,
    reason: 'ミシシッピチズガメと並ぶ人気チズガメ。甲羅のキールがより鋭く、ミシシッピ川流域に生息。流水好みで水質管理が重要。オス・メスの体格差が大きいため飼育スペースの計画が必要。',
    specs: { '最大甲長': 'オス10cm/メス22cm', '水槽サイズ': '60〜90cm', '水温': '20〜26℃', '難易度': '★★☆' },
    coreSpecs: { size: 'オス10cm/メス22cm', temp: '20〜26℃', lifespan: '15〜25年', diet: '雑食（水生無脊椎動物中心）' },
    extraSpecs: { tankSize: '60〜90cm' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.medium_tank||0) >= 2 && (s.maintenance||0) >= 2; },
    score: function(s){ return (s.medium_tank||0)+(s.maintenance||0)+(s.beauty||0)+(s.observational||0)+(s.na_water||0)+(s.cool_climate||0); }
  },
  { name: 'メキシカンジャイアントマスク', latin: 'Staurotypus triporcatus', emoji: '🦕', difficulty: '上級', size: 'L（30〜40cm）', cites: null, legal: null,
    reason: 'メキシコ・中米産の大型ドロガメ科。スジオオニオイガメの近縁でさらに大型。3本の明確なキールを持ち噛みつき力が非常に強い。素手での取り扱い厳禁。本格マニア向けの希少種。',
    specs: { '最大甲長': '40cm（メス）', '水槽サイズ': '90cm〜', '水温': '25〜30℃', '難易度': '★★★' },
    coreSpecs: { size: '40cm（メス）', temp: '25〜30℃', lifespan: '20〜40年', diet: '雑食（肉食寄り）' },
    extraSpecs: { tankSize: '90cm〜' },
    links: [{ label: '半水棲ガメ 飼育ガイド', href: '../guide-semi.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.large_mud||0) >= 2 && (s.advanced||0) >= 2; },
    score: function(s){ return (s.large_mud||0)+(s.advanced||0)+(s.budget_high||0)+(s.expert||0)+(s.ultra_rare||0); }
  },
  { name: 'ハナガメ', latin: 'Mauremys sinensis', emoji: '🌸', difficulty: '入門〜中級', size: 'M（20〜25cm）', cites: null, legal: null,
    reason: '首のストライプが美しい東・東南アジア産の中型水棲ガメ。クサガメと近縁だが首筋の模様が鮮やかで観賞価値が高い。丈夫で飼育しやすく入門者にも向く。国内CBの流通もある。',
    specs: { '最大甲長': '25cm', '水槽サイズ': '60〜90cm', '水温': '20〜28℃', '難易度': '★☆☆' },
    coreSpecs: { size: '25cm', temp: '20〜28℃', lifespan: '20〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '60〜90cm' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.medium_tank||0) >= 1 && (s.beginner||0) >= 1; },
    score: function(s){ return (s.medium_tank||0)+(s.beginner||0)+(s.beauty||0)+(s.active||0)+(s.asia_water||0)+(s.cool_climate||0)+(s.mainstream||0); }
  },
  { name: 'トウブドロガメ', latin: 'Kinosternon subrubrum subrubrum', emoji: '🌊', difficulty: '入門', size: 'S（9〜12cm）', cites: null, legal: null,
    reason: 'ニオイガメと並ぶ入門向けの小型ドロガメ。北米東部の湿地・沼地に生息し、30〜45cm水槽から飼育可能。水陸両用で活発に動く姿が愛らしい。比較的温和で初心者にも向く。',
    specs: { '最大甲長': '12cm', '水槽サイズ': '30〜45cm', '水温': '22〜27℃', '難易度': '★☆☆' },
    coreSpecs: { size: '12cm', temp: '22〜27℃', lifespan: '20〜30年', diet: '雑食' },
    extraSpecs: { tankSize: '30〜45cm' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.small_tank||0) >= 2 && (s.beginner||0) >= 1; },
    score: function(s){ return (s.small_tank||0)+(s.beginner||0)+(s.mud_lover||0)+(s.observational||0)+(s.na_water||0)+(s.warm_climate||0)+(s.mainstream||0); }
  },
  { name: 'カンバーランドスライダー', latin: 'Trachemys scripta troostii', emoji: '🌿', difficulty: '入門', size: 'M（18〜28cm）', cites: null, legal: null,
    reason: 'キバラガメと同じスライダー系の一亜種。テネシー川流域原産で、腹甲の赤みが特徴的。キバラガメよりやや色彩が渋く、入門者向けの丈夫で飼育しやすい水棲ガメ。',
    specs: { '最大甲長': '28cm', '水槽サイズ': '60〜90cm', '水温': '22〜28℃', '難易度': '★☆☆' },
    coreSpecs: { size: '28cm', temp: '22〜28℃', lifespan: '20〜30年', diet: '雑食（幼体肉食寄り）' },
    extraSpecs: { tankSize: '60〜90cm' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.medium_tank||0) >= 1 && (s.active||0) >= 2; },
    score: function(s){ return (s.medium_tank||0)+(s.active||0)+(s.beginner||0)+(s.mainstream||0)+(s.swimmer||0)+(s.na_water||0)+(s.warm_climate||0); }
  },
  { name: 'キタチズガメ', latin: 'Graptemys geographica', emoji: '🗾', difficulty: '中級', size: 'M（オス10cm/メス28cm）', cites: null, legal: null,
    reason: 'チズガメ属の基本種。甲羅に地図状の模様が入る美麗種で、オス・メスで体格差が大きい。水質管理が重要で、適切なフィルターと水温管理ができる中級者向け。',
    specs: { '最大甲長': 'オス10cm/メス28cm', '水槽サイズ': '60〜90cm', '水温': '20〜26℃', '難易度': '★★☆' },
    coreSpecs: { size: 'オス10cm/メス28cm', temp: '20〜26℃', lifespan: '15〜25年', diet: '雑食（水生無脊椎動物中心）' },
    extraSpecs: { tankSize: '60〜90cm' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.medium_tank||0) >= 2 && (s.maintenance||0) >= 2; },
    score: function(s){ return (s.medium_tank||0)+(s.maintenance||0)+(s.beauty||0)+(s.observational||0)+(s.na_water||0)+(s.cool_climate||0)+(s.bottom_dweller||0); }
  },
  { name: 'テキサスチズガメ', latin: 'Graptemys versa', emoji: '⭐', difficulty: '中〜上級', size: 'S（オス7cm/メス12cm）', cites: null, legal: null,
    reason: 'チズガメ属で最小クラスの小型種。テキサス州グアダルーペ川水系固有種。コンパクトな体格と美しい甲羅模様が人気。流水を好み酸素豊富な水質が必要な上級向け種。',
    specs: { '最大甲長': 'オス7cm/メス12cm', '水槽サイズ': '45〜60cm', '水温': '20〜26℃', '難易度': '★★★' },
    coreSpecs: { size: 'オス7cm/メス12cm', temp: '20〜26℃', lifespan: '15〜20年', diet: '雑食（軟体動物・昆虫中心）' },
    extraSpecs: { tankSize: '45〜60cm' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.small_tank||0) >= 1 && (s.maintenance||0) >= 2 && (s.advanced||0) >= 1; },
    score: function(s){ return (s.small_tank||0)+(s.maintenance||0)+(s.beauty||0)+(s.observational||0)+(s.na_water||0)+(s.collector||0)+(s.cool_climate||0); }
  },
  { name: 'サビーンチズガメ', latin: 'Graptemys sabinensis', emoji: '🔷', difficulty: '中〜上級', size: 'M（オス9cm/メス18cm）', cites: null, legal: null,
    reason: 'テキサス州サビン川水系固有のチズガメ。甲羅のキールが目立ちチズガメらしい美麗な模様を持つ。流水・高水質を好む扱いにくさはあるが、コレクター人気が高い希少種。',
    specs: { '最大甲長': 'オス9cm/メス18cm', '水槽サイズ': '60cm〜', '水温': '20〜26℃', '難易度': '★★★' },
    coreSpecs: { size: 'オス9cm/メス18cm', temp: '20〜26℃', lifespan: '15〜25年', diet: '雑食（軟体動物中心）' },
    extraSpecs: { tankSize: '60cm〜' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.medium_tank||0) >= 2 && (s.maintenance||0) >= 2 && (s.collector||0) >= 1; },
    score: function(s){ return (s.medium_tank||0)+(s.maintenance||0)+(s.beauty||0)+(s.collector||0)+(s.na_water||0)+(s.rare_water||0)+(s.cool_climate||0); }
  },
  { name: 'アラバマチズガメ', latin: 'Graptemys pulchra', emoji: '💎', difficulty: '中〜上級', size: 'M（オス10cm/メス25cm）', cites: null, legal: null,
    reason: 'アラバマ州・フロリダ州西部の河川系に生息するチズガメ。メスの甲幅が特に広くなる大型個体が魅力。水質・酸素量への要求が高く、本格的な水棲ガメ飼育を楽しみたい上級者向け。',
    specs: { '最大甲長': 'オス10cm/メス25cm', '水槽サイズ': '60〜90cm', '水温': '20〜26℃', '難易度': '★★★' },
    coreSpecs: { size: 'オス10cm/メス25cm', temp: '20〜26℃', lifespan: '15〜25年', diet: '雑食（水生無脊椎動物中心）' },
    extraSpecs: { tankSize: '60〜90cm' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.medium_tank||0) >= 2 && (s.maintenance||0) >= 3 && (s.advanced||0) >= 2; },
    score: function(s){ return (s.medium_tank||0)+(s.maintenance||0)+(s.beauty||0)+(s.advanced||0)+(s.na_water||0)+(s.collector||0)+(s.cool_climate||0); }
  },
  { name: 'アジアコガシラドロガメ', latin: 'Siebenrockiella crassicollis', emoji: '🖤', difficulty: '中〜上級', size: 'M（16〜20cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '東南アジア産の黒い水棲ガメ。全身真っ黒の独特の容姿が魅力で、低地の沼・湿地・溜池に生息。高水温と水質管理が重要。CITES II種のため国内CBの取引証明書確認が必要。',
    specs: { '最大甲長': '20cm', '水槽サイズ': '60cm〜', '水温': '24〜30℃', '難易度': '★★☆' },
    coreSpecs: { size: '20cm', temp: '24〜30℃', lifespan: '20〜30年', diet: '雑食（動物食強め）' },
    extraSpecs: { tankSize: '60cm〜' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.medium_tank||0) >= 1 && (s.intermediate||0) >= 1 && (s.asia_water||0) >= 1; },
    score: function(s){ return (s.medium_tank||0)+(s.intermediate||0)+(s.observational||0)+(s.asia_water||0)+(s.tropical_climate||0)+(s.collector||0)+(s.beauty||0); }
  }
],

// ==================== ヤマガメ・ハコガメルート ====================
forest: [
  { name: 'キボシイシガメ', latin: 'Clemmys guttata', emoji: '✨', difficulty: '中級', size: 'S（10〜12cm）', cites: 'CITES II', legal: null,
    reason: '黒い甲羅に黄色の水玉模様が美しい北米産。45〜60cm程度の半水棲ケージで飼育可能。低温を好む温帯種で夏の保冷管理が必要。',
    specs: { '最大甲長': '12cm', 'タイプ': '半水棲', '温度': '18〜25℃', '難易度': '★★☆' },
    coreSpecs: { size: '12cm', temp: '18〜25℃', lifespan: '20〜50年', diet: '雑食' },
    extraSpecs: {},
    links: [{ label: '半水棲ガメ 飼育ガイド', href: '../guide-semi.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.s_size||0) >= 2 && (s.semi_aquatic||0) >= 1; },
    score: function(s){ return (s.s_size||0)+(s.semi_aquatic||0)+(s.intermediate||0)+(s.na_box||0)*2+(s.ya_ma||0)+(s.cool_climate||0); }
  },
  { name: 'モリイシガメ', latin: 'Glyptemys insculpta', emoji: '🍁', difficulty: '中〜上級', size: 'M（15〜20cm）', cites: 'CITES II', legal: null,
    reason: '甲羅に年輪のような刻みと橙色の模様が美しい北米産。低温を好む温帯種で夏の保冷が必要。半水棲で陸場と水場を行き来する。',
    specs: { '最大甲長': '20cm', 'タイプ': '半水棲', '温度': '16〜24℃', '難易度': '★★☆' },
    coreSpecs: { size: '20cm', temp: '16〜24℃', lifespan: '20〜50年', diet: '雑食' },
    extraSpecs: {},
    links: [{ label: '半水棲ガメ 飼育ガイド', href: '../guide-semi.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.s_size||0) >= 1 && (s.cooling||0) >= 1 && (s.semi_aquatic||0) >= 1; },
    score: function(s){ return (s.s_size||0)+(s.cooling||0)+(s.semi_aquatic||0)+(s.intermediate||0)+(s.na_box||0)+(s.ya_ma||0); }
  },
  { name: 'スペングラーヤマガメ', latin: 'Geoemyda spengleri', emoji: '🌿', difficulty: '中〜上級', size: 'S（10〜14cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '小型で独特の容姿が人気の森林棲ヤマガメ。夏の高温に弱く保冷管理が必須。動物性タンパクを好む雑食性で、ユニークな飼育体験ができます。著者も飼育中。',
    specs: { '最大甲長': '14cm', 'タイプ': '森林棲', '温度': '20〜27℃', '難易度': '★★★' },
    coreSpecs: { size: '14cm', temp: '20〜27℃', lifespan: '20〜40年', diet: '雑食' },
    extraSpecs: {},
    links: [{ label: 'ヤマガメ・ハコガメ 飼育ガイド', href: '../guide-moist.html' }], asin: null,
    slug: 'spenglers-leaf-turtle', hasPage: true,
    match: function(s){ return (s.s_size||0) >= 2 && (s.cooling||0) >= 2; },
    score: function(s){ return (s.s_size||0)+(s.cooling||0)+(s.advanced||0)+(s.advanced_env||0)+(s.ya_ma||0); }
  },
  { name: 'ヒラセガメ', latin: 'Pyxidea mouhotii', emoji: '🪨', difficulty: '中〜上級', size: 'M（15〜18cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '扁平な甲羅が特徴の東南アジア産ヤマガメ。夏の保冷管理と高湿度維持が重要。著者も飼育中で、落ち着いた性格が魅力。',
    specs: { '最大甲長': '18cm', 'タイプ': '森林棲', '温度': '20〜28℃', '難易度': '★★★' },
    coreSpecs: { size: '18cm', temp: '20〜28℃', lifespan: '30〜50年', diet: '雑食' },
    extraSpecs: {},
    links: [{ label: 'ヤマガメ・ハコガメ 飼育ガイド', href: '../guide-moist.html' }], asin: null,
    slug: 'hirase-turtle', hasPage: true,
    match: function(s){ return (s.m_size||0) >= 1 && (s.cooling||0) >= 2; },
    score: function(s){ return (s.m_size||0)+(s.cooling||0)+(s.advanced||0)+(s.advanced_env||0)+(s.ya_ma||0); }
  },
  { name: 'アカスジヤマガメ', latin: 'Rhinoclemmys pulcherrima', emoji: '🔴', difficulty: '中〜上級', size: 'M（17〜20cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '甲羅と頭部に鮮やかな赤いラインが走る美しい中米産ヤマガメ。半陸棲で湿度管理が必要。マンヤマガメとの区別に注意。',
    specs: { '最大甲長': '20cm', 'タイプ': '半陸棲', '温度': '24〜30℃', '難易度': '★★☆' },
    coreSpecs: { size: '20cm', temp: '24〜30℃', lifespan: '20〜50年', diet: '雑食' },
    extraSpecs: {},
    links: [{ label: 'ヤマガメ・ハコガメ 飼育ガイド', href: '../guide-moist.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.s_size||0) >= 1 && (s.cooling||0) >= 2 && (s.advanced_env||0) >= 2; },
    score: function(s){ return (s.s_size||0)+(s.cooling||0)+(s.advanced_env||0)+(s.advanced||0)+(s.ya_ma||0); }
  },
  { name: 'ネンリンヤマガメ', latin: 'Rhinoclemmys annulata', emoji: '🌀', difficulty: '中〜上級', size: 'M（18〜20cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '甲羅に年輪のような輪状の模様が美しい中南米産ヤマガメ。半陸棲で高湿度と水場が必要。国内CB流通確認済み。',
    specs: { '最大甲長': '20cm', 'タイプ': '半陸棲', '温度': '24〜30℃', '難易度': '★★☆' },
    coreSpecs: { size: '20cm', temp: '24〜30℃', lifespan: '20〜50年', diet: '雑食' },
    extraSpecs: {},
    links: [{ label: 'ヤマガメ・ハコガメ 飼育ガイド', href: '../guide-moist.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.m_size||0) >= 1 && (s.advanced_env||0) >= 2 && (s.semi_aquatic||0) >= 1; },
    score: function(s){ return (s.m_size||0)+(s.advanced_env||0)+(s.semi_aquatic||0)+(s.advanced||0)+(s.ya_ma||0); }
  },
  { name: 'マンヤマガメ', latin: 'Rhinoclemmys pulcherrima manni', emoji: '🎨', difficulty: '中〜上級', size: 'M（17〜20cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '古代民族の陶器のような鮮やかな色彩が特徴の中米産ヤマガメ。かめぢから・ぶりくら路面店での流通確認済み。果物・人工飼料なんでも食べる飼育しやすさが◎。',
    specs: { '最大甲長': '20cm', 'タイプ': '半陸棲', '温度': '24〜30℃', '難易度': '★★☆' },
    coreSpecs: { size: '20cm', temp: '24〜30℃', lifespan: '20〜50年', diet: '雑食' },
    extraSpecs: {},
    links: [{ label: 'ヤマガメ・ハコガメ 飼育ガイド', href: '../guide-moist.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.m_size||0) >= 1 && (s.semi_aquatic||0) >= 1 && (s.intermediate||0) >= 1; },
    score: function(s){ return (s.m_size||0)+(s.semi_aquatic||0)+(s.intermediate||0)+(s.advanced_env||0)+(s.ya_ma||0); }
  },
  { name: 'ニカラグアクジャクガメ', latin: 'Rhinoclemmys pulcherrima incisa', emoji: '🦚', difficulty: '中〜上級', size: 'M（15〜20cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '鮮やかな模様を持つ中米産ヤマガメ。ぶりくら2025出品リストにニカラグアクジャクガメとして記載。半陸棲で水場と陸場を行き来する。高湿度環境が必要。',
    specs: { '最大甲長': '20cm', 'タイプ': '半陸棲', '温度': '24〜29℃', '難易度': '★★☆' },
    coreSpecs: { size: '20cm', temp: '24〜29℃', lifespan: '20〜50年', diet: '雑食' },
    extraSpecs: {},
    links: [{ label: 'ヤマガメ・ハコガメ 飼育ガイド', href: '../guide-moist.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.m_size||0) >= 1 && (s.semi_aquatic||0) >= 2 && (s.advanced_env||0) >= 1; },
    score: function(s){ return (s.m_size||0)+(s.semi_aquatic||0)+(s.advanced_env||0)+(s.intermediate||0)+(s.ya_ma||0); }
  },
  { name: 'ミツユビハコガメ', latin: 'Terrapene carolina triunguis', emoji: '📦', difficulty: '中〜上級', size: 'M（12〜18cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '後肢が3本指の北米産ハコガメ。腹甲を完全に閉じられる独自構造が特徴。雑食性で飼育食への移行がしやすい。著者も飼育中。',
    specs: { '最大甲長': '18cm', 'タイプ': '陸棲', '温度': '22〜28℃', '難易度': '★★☆' },
    coreSpecs: { size: '18cm', temp: '22〜28℃', lifespan: '30〜50年', diet: '雑食' },
    extraSpecs: {},
    links: [{ label: 'ヤマガメ・ハコガメ 飼育ガイド', href: '../guide-moist.html' }], asin: null,
    slug: 'three-toed-box-turtle', hasPage: true,
    match: function(s){ return (s.terrestrial||0) >= 2 && (s.m_size||0) >= 1; },
    score: function(s){ return (s.terrestrial||0)+(s.m_size||0)+(s.intermediate||0)+(s.advanced_env||0)+(s.na_box||0); }
  },
  { name: 'トウブハコガメ', latin: 'Terrapene carolina carolina', emoji: '🍁', difficulty: '中〜上級', size: 'M（15〜20cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '北米産ハコガメの基亜種。国内CBの流通も盛ん。腹甲全体を閉じられる独特の能力をもつ。雑食性で飼育食への移行も比較的容易。',
    specs: { '最大甲長': '20cm', 'タイプ': '陸棲', '温度': '22〜28℃', '難易度': '★★☆' },
    coreSpecs: { size: '20cm', temp: '22〜28℃', lifespan: '30〜80年', diet: '雑食' },
    extraSpecs: {},
    links: [{ label: 'ヤマガメ・ハコガメ 飼育ガイド', href: '../guide-moist.html' }], asin: null,
    slug: 'eastern-box-turtle', hasPage: true,
    match: function(s){ return (s.terrestrial||0) >= 2 && (s.m_size||0) >= 1; },
    score: function(s){ return (s.terrestrial||0)+(s.m_size||0)+(s.intermediate||0)+(s.na_box||0); }
  },
  { name: 'ガルフコーストハコガメ', latin: 'Terrapene carolina major', emoji: '🌊', difficulty: '中〜上級', size: 'M〜L（18〜22cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: 'ハコガメの中で最も大型になる亜種。やや湿度の高い環境を好む。中型〜大型の陸棲ガメを求める中上級者に適する。',
    specs: { '最大甲長': '22cm', 'タイプ': '陸棲', '温度': '22〜28℃', '難易度': '★★☆' },
    coreSpecs: { size: '22cm', temp: '22〜28℃', lifespan: '20〜50年', diet: '雑食' },
    extraSpecs: {},
    links: [{ label: 'ヤマガメ・ハコガメ 飼育ガイド', href: '../guide-moist.html' }], asin: null,
    slug: 'gulf-coast-box-turtle', hasPage: true,
    match: function(s){ return (s.terrestrial||0) >= 2 && (s.m_size||0) >= 2 && (s.advanced_env||0) >= 1; },
    score: function(s){ return (s.terrestrial||0)+(s.m_size||0)+(s.intermediate||0)+(s.advanced_env||0)+(s.na_box||0); }
  },
  { name: 'フロリダハコガメ', latin: 'Terrapene bauri', emoji: '🌴', difficulty: '中〜上級', size: 'M（11〜15cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: 'フロリダ産の小型ハコガメ。甲羅に放射状の美しい模様がある。他のハコガメより小さく、50cm程度のケージでも飼育可能。',
    specs: { '最大甲長': '15cm', 'タイプ': '陸棲', '温度': '23〜29℃', '難易度': '★★☆' },
    coreSpecs: { size: '15cm', temp: '23〜29℃', lifespan: '20〜50年', diet: '雑食' },
    extraSpecs: {},
    links: [{ label: 'ヤマガメ・ハコガメ 飼育ガイド', href: '../guide-moist.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.terrestrial||0) >= 2 && (s.s_size||0) >= 1 && (s.intermediate||0) >= 1; },
    score: function(s){ return (s.terrestrial||0)+(s.s_size||0)+(s.intermediate||0)+(s.na_box||0); }
  },
  { name: 'キタニシキハコガメ', latin: 'Terrapene ornata ornata', emoji: '💎', difficulty: '中〜上級', size: 'M（11〜15cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '甲羅に黄色のニシキ模様が入る美しいハコガメ。乾燥気味の環境を好み草食傾向が強い。北米ハコガメの中でも個性的な一種。',
    specs: { '最大甲長': '15cm', 'タイプ': '陸棲', '温度': '23〜30℃', '難易度': '★★☆' },
    coreSpecs: { size: '15cm', temp: '23〜30℃', lifespan: '20〜50年', diet: '雑食' },
    extraSpecs: {},
    links: [{ label: 'ヤマガメ・ハコガメ 飼育ガイド', href: '../guide-moist.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.terrestrial||0) >= 3 && (s.m_size||0) >= 1 && (s.intermediate||0) >= 1; },
    score: function(s){ return (s.terrestrial||0)+(s.m_size||0)+(s.intermediate||0)+(s.advanced_env||0)+(s.na_box||0); }
  },
  { name: 'タイワンセマルハコガメ', latin: 'Cuora flavomarginata evelynae', emoji: '🟠', difficulty: '中〜上級', size: 'M（14〜18cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '甲羅の縁がオレンジ色に縁どられた美しい台湾産ハコガメ。CB個体は流通している。沖縄産は天然記念物で全く別扱い。必ずCB証明書を確認のこと。',
    specs: { '最大甲長': '18cm', 'タイプ': '半水棲', '温度': '24〜29℃', '難易度': '★★☆' },
    coreSpecs: { size: '18cm', temp: '24〜29℃', lifespan: '20〜50年', diet: '雑食' },
    extraSpecs: {},
    links: [{ label: 'ヤマガメ・ハコガメ 飼育ガイド', href: '../guide-moist.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.semi_aquatic||0) >= 2 && (s.m_size||0) >= 1 && (s.intermediate||0) >= 1; },
    score: function(s){ return (s.semi_aquatic||0)+(s.m_size||0)+(s.advanced_env||0)+(s.intermediate||0)+(s.asia_box||0); }
  },
  { name: 'マレーハコガメ', latin: 'Cuora amboinensis', emoji: '🌊', difficulty: '中〜上級', size: 'M（18〜20cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '東南アジア広域に分布する半水棲のハコガメ。水場・陸場を行き来する。高温多湿を好みアジア的な雰囲気がある。',
    specs: { '最大甲長': '20cm', 'タイプ': '半水棲', '温度': '26〜30℃', '難易度': '★★☆' },
    coreSpecs: { size: '20cm', temp: '26〜30℃', lifespan: '20〜50年', diet: '雑食' },
    extraSpecs: {},
    links: [{ label: 'ヤマガメ・ハコガメ 飼育ガイド', href: '../guide-moist.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.semi_aquatic||0) >= 2 && (s.m_size||0) >= 1; },
    score: function(s){ return (s.semi_aquatic||0)+(s.m_size||0)+(s.advanced_env||0)+(s.asia_box||0); }
  },
  { name: 'チュウゴクセマルハコガメ', latin: 'Cuora flavomarginata', emoji: '🇨🇳', difficulty: '中〜上級', size: 'M（14〜18cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '中国本土産のセマルハコガメ。CB個体の流通がある。タイワン産と同様の管理で飼育できるが亜種の証明書をしっかり確認することが重要。',
    specs: { '最大甲長': '18cm', 'タイプ': '半水棲', '温度': '24〜29℃', '難易度': '★★☆' },
    coreSpecs: { size: '18cm', temp: '24〜29℃', lifespan: '20〜50年', diet: '雑食' },
    extraSpecs: {},
    links: [{ label: 'ヤマガメ・ハコガメ 飼育ガイド', href: '../guide-moist.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.semi_aquatic||0) >= 2 && (s.m_size||0) >= 1 && (s.advanced||0) >= 1; },
    score: function(s){ return (s.semi_aquatic||0)+(s.m_size||0)+(s.advanced_env||0)+(s.advanced||0)+(s.asia_box||0); }
  },
  { name: 'モエギハコガメ', latin: 'Cuora galbinifrons', emoji: '💚', difficulty: '上級', size: 'M（15〜19cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '萌黄色の甲羅が美しいアジア産ハコガメ。流通量が限られ上級者向き。湿度高め・やや低めの温度管理が必要。',
    specs: { '最大甲長': '19cm', 'タイプ': '半陸棲', '温度': '22〜26℃', '難易度': '★★★' },
    coreSpecs: { size: '19cm', temp: '22〜26℃', lifespan: '20〜50年', diet: '雑食' },
    extraSpecs: {},
    links: [{ label: 'ヤマガメ・ハコガメ 飼育ガイド', href: '../guide-moist.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.advanced||0) >= 2 && (s.advanced_env||0) >= 2 && (s.cooling||0) >= 1; },
    score: function(s){ return (s.advanced||0)+(s.advanced_env||0)+(s.cooling||0)+(s.m_size||0)+(s.asia_box||0); }
  },
  { name: 'オルナータハコガメ', latin: 'Cuora ornata', emoji: '🎨', difficulty: '上級', size: 'M（17〜20cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '甲羅の美しい模様が特徴のアジア産ハコガメ。モエギに次ぐ希少性で上級者向き。湿度と温度の精密管理が必要。',
    specs: { '最大甲長': '20cm', 'タイプ': '半陸棲', '温度': '22〜27℃', '難易度': '★★★' },
    coreSpecs: { size: '20cm', temp: '22〜27℃', lifespan: '20〜50年', diet: '雑食' },
    extraSpecs: {},
    links: [{ label: 'ヤマガメ・ハコガメ 飼育ガイド', href: '../guide-moist.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.terrestrial||0) >= 2 && (s.advanced||0) >= 2 && (s.advanced_env||0) >= 2; },
    score: function(s){ return (s.terrestrial||0)+(s.advanced||0)+(s.advanced_env||0)+(s.asia_box||0); }
  },
  { name: 'ミスジハコガメ', latin: 'Cuora trifasciata', emoji: '🏆', difficulty: '上級', size: 'M（17〜21cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '3本のラインが走る甲羅が特徴のアジア産超希少ハコガメ。高価で流通が非常に少ない。CB個体を入手できれば本格的なアジアガメ飼育の頂点。',
    specs: { '最大甲長': '21cm', 'タイプ': '半水棲', '温度': '22〜27℃', '難易度': '★★★' },
    coreSpecs: { size: '21cm', temp: '22〜27℃', lifespan: '20〜50年', diet: '雑食' },
    extraSpecs: {},
    links: [{ label: 'ヤマガメ・ハコガメ 飼育ガイド', href: '../guide-moist.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.semi_aquatic||0) >= 1 && (s.advanced||0) >= 3 && (s.advanced_env||0) >= 3; },
    score: function(s){ return (s.semi_aquatic||0)+(s.advanced||0)+(s.advanced_env||0)+(s.cooling||0)+(s.asia_box||0); }
  },
  { name: 'ウッドタートル', latin: 'Glyptemys insculpta', emoji: '🪵', difficulty: '上級', size: 'M（17〜22cm）', cites: null, legal: null,
    reason: '北米産の半陸棲ガメ。高い知能で知られ、ラビリンス実験でマウスと同等の学習能力が報告されている。木彫のような甲羅模様が美しい。冬眠が必要で高温に弱い飼育難種。',
    specs: { '最大甲長': '22cm', 'タイプ': '半陸棲', '温度': '15〜24℃', '難易度': '★★★' },
    coreSpecs: { size: '22cm', temp: '15〜24℃', lifespan: '40〜60年', diet: '雑食（葉・果実・ミミズ等）' },
    extraSpecs: {},
    links: [{ label: 'ヤマガメ・ハコガメ 飼育ガイド', href: '../guide-moist.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.semi_aquatic||0) >= 2 && (s.cooling||0) >= 2 && (s.advanced||0) >= 2; },
    score: function(s){ return (s.semi_aquatic||0)+(s.cooling||0)+(s.advanced||0)+(s.collector||0)+(s.ya_ma||0)+(s.cool_climate||0); }
  },
  { name: 'メキシコハコガメ', latin: 'Terrapene mexicana', emoji: '🌵', difficulty: '上級', size: 'M（14〜18cm）', cites: null, legal: null,
    reason: 'メキシコ東部に生息するハコガメ。北米産ハコガメより乾燥への適応幅がやや広い。腹甲を完全に閉じられるハコガメ固有の防御機構を持つ。国内流通が非常に少なくコレクター向け。',
    specs: { '最大甲長': '18cm', 'タイプ': '陸棲', '温度': '22〜30℃', '難易度': '★★★' },
    coreSpecs: { size: '18cm', temp: '22〜30℃', lifespan: '30〜60年', diet: '雑食' },
    extraSpecs: {},
    links: [{ label: 'ヤマガメ・ハコガメ 飼育ガイド', href: '../guide-moist.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.terrestrial||0) >= 2 && (s.advanced||0) >= 2 && (s.collector||0) >= 1; },
    score: function(s){ return (s.terrestrial||0)+(s.m_size||0)+(s.advanced||0)+(s.collector||0)+(s.na_box||0)+(s.ultra_rare||0); }
  },
  { name: 'ノコヘリマルガメ', latin: 'Cyclemys dentata', emoji: '🌿', difficulty: '中〜上級', size: 'M（20〜25cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: '東南アジア産の半水棲ガメ。甲羅の縁が鋸歯状でノコギリのような独特の形状が特徴。若い個体はより水棲傾向が強く、成熟につれ陸棲傾向が増す興味深い種。CITES II。',
    specs: { '最大甲長': '25cm', 'タイプ': '半水棲→半陸棲', '温度': '24〜30℃', '難易度': '★★☆' },
    coreSpecs: { size: '25cm', temp: '24〜30℃', lifespan: '20〜40年', diet: '雑食（植物・水生昆虫）' },
    extraSpecs: {},
    links: [{ label: 'ヤマガメ・ハコガメ 飼育ガイド', href: '../guide-moist.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.semi_aquatic||0) >= 2 && (s.intermediate||0) >= 1; },
    score: function(s){ return (s.semi_aquatic||0)+(s.intermediate||0)+(s.m_size||0)+(s.tropical_climate||0)+(s.asia_water||0)+(s.ya_ma||0)+(s.humid_env||0); }
  },
  { name: 'ニシキハコガメ（オルナータ）', latin: 'Terrapene ornata luteola', emoji: '🏵️', difficulty: '上級', size: 'M（11〜15cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: 'テキサス州〜メキシコに分布するニシキハコガメの亜種。乾燥耐性が高く放射状の美しい甲羅模様が特徴。乾燥系環境を好むハコガメで、キタニシキハコガメよりさらに乾燥に強い。CITES II。',
    specs: { '最大甲長': '15cm', 'タイプ': '陸棲', '温度': '22〜32℃', '難易度': '★★★' },
    coreSpecs: { size: '15cm', temp: '22〜32℃', lifespan: '30〜50年', diet: '雑食（昆虫・果実・草）' },
    extraSpecs: {},
    links: [{ label: 'ヤマガメ・ハコガメ 飼育ガイド', href: '../guide-moist.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.terrestrial||0) >= 2 && (s.advanced||0) >= 2; },
    score: function(s){ return (s.terrestrial||0)+(s.s_size||0)+(s.advanced||0)+(s.collector||0)+(s.na_box||0)+(s.dry_env||0); }
  }
],

// ==================== マニアック・特殊ルート ====================
exotic: [
  { name: 'スパイニースッポン', latin: 'Apalone spinifera', emoji: '💫', difficulty: '上級', size: 'L（30〜50cm）', cites: null, legal: null,
    reason: '最も流通量の多いスッポン属。砂底必須・水流弱め・甲羅を傷つけないよう注意。独特の柔らかい甲羅と素早い動きが魅力。',
    specs: { '最大甲長': '50cm（メス）', '水槽サイズ': '90cm〜', '底床': '細かい砂必須', '水温': '24〜30℃' },
    coreSpecs: { size: '50cm（メス）', temp: '24〜30℃', lifespan: '20〜40年', diet: '肉食寄り雑食' },
    extraSpecs: { tankSize: '90cm〜', substrate: '細かい砂必須' },
    links: [{ label: 'スッポン・ヘビクビガメ 飼育ガイド', href: '../guide-softshell.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.softshell||0) >= 3; },
    score: function(s){ return (s.softshell||0)+(s.advanced||0)+(s.budget_high||0)+(s.accessible||0)*2; }
  },
  { name: 'スムーススッポン', latin: 'Apalone mutica', emoji: '🫧', difficulty: '上級', size: 'L（25〜45cm）', cites: null, legal: null,
    reason: 'スパイニースッポンよりキールが目立たない滑らかな甲羅を持つ。砂底必須・水流弱め。スッポン属の中でも温和な個体が多い。',
    specs: { '最大甲長': '45cm（メス）', '水槽サイズ': '90cm〜', '底床': '細かい砂必須', '水温': '24〜30℃' },
    coreSpecs: { size: '45cm（メス）', temp: '24〜30℃', lifespan: '20〜40年', diet: '肉食寄り雑食' },
    extraSpecs: { tankSize: '90cm〜', substrate: '細かい砂必須' },
    links: [{ label: 'スッポン・ヘビクビガメ 飼育ガイド', href: '../guide-softshell.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.softshell||0) >= 2 && (s.budget_high||0) >= 1; },
    score: function(s){ return (s.softshell||0)+(s.advanced||0)+(s.budget_high||0); }
  },
  { name: 'フロリダスッポン', latin: 'Apalone ferox', emoji: '🐊', difficulty: '上級', size: 'L（35〜60cm）', cites: null, legal: null,
    reason: 'スッポン属最大種のひとつ。非常に攻撃的で飼育難度が高い。本格的なソフトシェル飼育に挑戦したい経験者向け。',
    specs: { '最大甲長': '60cm（メス）', '水槽サイズ': '120cm〜', '底床': '細かい砂必須', '水温': '25〜30℃' },
    coreSpecs: { size: '60cm（メス）', temp: '25〜30℃', lifespan: '20〜40年', diet: '肉食寄り雑食' },
    extraSpecs: { tankSize: '120cm〜', substrate: '細かい砂必須' },
    links: [{ label: 'スッポン・ヘビクビガメ 飼育ガイド', href: '../guide-softshell.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.softshell||0) >= 2 && (s.budget_max||0) >= 1; },
    score: function(s){ return (s.softshell||0)+(s.advanced||0)+(s.budget_max||0)+(s.expert||0)+(s.ultra_rare||0)*2; }
  },
  { name: 'スッポンモドキ', latin: 'Carettochelys insculpta', emoji: '🌊', difficulty: '上級', size: 'XL（50〜70cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: 'ニューギニア・オーストラリア北部産の大型種。前肢がウミガメのようなヒレ状。26〜30℃の高水温と広い水槽が必須の本格飼育種。',
    specs: { '最大甲長': '70cm', '水槽サイズ': '150cm〜', '底床': '砂利〜砂', '水温': '26〜30℃' },
    coreSpecs: { size: '70cm', temp: '26〜30℃', lifespan: '20〜40年', diet: '雑食（植物多め）' },
    extraSpecs: { tankSize: '150cm〜', substrate: '砂利〜砂' },
    links: [{ label: 'スッポン・ヘビクビガメ 飼育ガイド', href: '../guide-softshell.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.softshell||0) >= 2 && (s.budget_max||0) >= 2; },
    score: function(s){ return (s.softshell||0)+(s.advanced||0)+(s.budget_max||0)+(s.expert||0)+(s.ultra_rare||0); }
  },
  { name: 'スッポン（シナスッポン）', latin: 'Pelodiscus sinensis', emoji: '🍵', difficulty: '中〜上級', size: 'L（25〜35cm）', cites: null, legal: null,
    reason: '食用としても知られる東アジア産スッポン。ペットとしての飼育者も多く国内流通が安定している。砂底必須・嚙みつき注意。軟らかい甲羅と独特の動きが面白い。',
    specs: { '最大甲長': '35cm', '水槽サイズ': '90cm〜', '底床': '細かい砂必須', '水温': '24〜30℃' },
    coreSpecs: { size: '35cm', temp: '24〜30℃', lifespan: '20〜40年', diet: '肉食寄り雑食' },
    extraSpecs: { tankSize: '90cm〜', substrate: '細かい砂必須' },
    links: [{ label: 'スッポン・ヘビクビガメ 飼育ガイド', href: '../guide-softshell.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.softshell||0) >= 2 && (s.intermediate||0) >= 1; },
    score: function(s){ return (s.softshell||0)+(s.intermediate||0)+(s.budget_high||0)+(s.accessible||0); }
  },
  { name: 'アルビノシナスッポン', latin: 'Pelodiscus sinensis（アルビノ）', emoji: '⬜', difficulty: '中〜上級', size: 'L（25〜35cm）', cites: null, legal: null,
    reason: '白〜クリーム色の体色が美しいシナスッポンのアルビノ個体。アクアスペースなど専門店で入荷確認済み。スッポンの迫力とアルビノの希少感を兼ね備えた観賞種。',
    specs: { '最大甲長': '35cm', '水槽サイズ': '90cm〜', '底床': '細かい砂必須', '水温': '24〜30℃' },
    coreSpecs: { size: '35cm', temp: '24〜30℃', lifespan: '20〜40年', diet: '肉食寄り雑食' },
    extraSpecs: { tankSize: '90cm〜', substrate: '細かい砂必須' },
    links: [{ label: 'スッポン・ヘビクビガメ 飼育ガイド', href: '../guide-softshell.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.softshell||0) >= 2 && (s.intermediate||0) >= 2; },
    score: function(s){ return (s.softshell||0)+(s.intermediate||0)+(s.budget_high||0)+(s.collector_grade||0); }
  },
  { name: 'ノーザンダイヤモンドバックテラピン', latin: 'Malaclemys terrapin terrapin', emoji: '💎', difficulty: '上級', size: 'M（15〜23cm）', cites: null, legal: null,
    reason: '汽水（海水と淡水の混合）で飼育する北米唯一の汽水ガメ。独特の菱形模様が美しく専門的な塩分管理が必要。ディープなマニア向き。',
    specs: { '最大甲長': '23cm', '水槽サイズ': '60cm〜', '塩分濃度': '0.5〜1.0%', '水温': '20〜28℃' },
    coreSpecs: { size: '23cm', temp: '20〜28℃', lifespan: '20〜40年', diet: '雑食' },
    extraSpecs: { tankSize: '60cm〜', salinity: '0.5〜1.0%' },
    links: [{ label: '汽水ガメ 飼育ガイド', href: '../guide-brackish.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.brackish||0) >= 3; },
    score: function(s){ return (s.brackish||0)+(s.advanced||0)+(s.budget_high||0)+(s.accessible||0)*2; }
  },
  { name: 'カロリナダイヤモンドバックテラピン', latin: 'Malaclemys terrapin centrata', emoji: '💠', difficulty: '上級', size: 'M（13〜21cm）', cites: null, legal: null,
    reason: '最も美しいとも言われるダイヤモンドバックテラピンの亜種。甲羅の同心円模様が見事。国内CB流通が盛んになっている。',
    specs: { '最大甲長': '21cm', '水槽サイズ': '60cm〜', '塩分濃度': '0.5〜1.0%', '水温': '20〜28℃' },
    coreSpecs: { size: '21cm', temp: '20〜28℃', lifespan: '20〜40年', diet: '雑食' },
    extraSpecs: { tankSize: '60cm〜', salinity: '0.5〜1.0%' },
    links: [{ label: '汽水ガメ 飼育ガイド', href: '../guide-brackish.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.brackish||0) >= 3 && (s.budget_high||0) >= 1; },
    score: function(s){ return (s.brackish||0)+(s.advanced||0)+(s.budget_high||0)+(s.expert||0)+(s.collector_grade||0); }
  },
  { name: 'オルナータダイヤモンドバックテラピン', latin: 'Malaclemys terrapin macrospilota', emoji: '🔶', difficulty: '上級', size: 'M（13〜20cm）', cites: null, legal: null,
    reason: 'フロリダ産の派手な模様を持つダイヤモンドバックテラピンの亜種。国内CB流通が盛ん（アクアスペース2024年入荷確認）。汽水管理が必要だが亜種中で最も流通が多い。',
    specs: { '最大甲長': '20cm', '水槽サイズ': '60cm〜', '塩分濃度': '0.5〜1.0%', '水温': '20〜28℃' },
    coreSpecs: { size: '20cm', temp: '20〜28℃', lifespan: '20〜40年', diet: '雑食' },
    extraSpecs: { tankSize: '60cm〜', salinity: '0.5〜1.0%' },
    links: [{ label: '汽水ガメ 飼育ガイド', href: '../guide-brackish.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.brackish||0) >= 3 && (s.budget_high||0) >= 2; },
    score: function(s){ return (s.brackish||0)+(s.budget_high||0)+(s.advanced||0)+(s.expert||0)+(s.collector_grade||0); }
  },
  { name: 'ヘビクビガメ', latin: 'Chelodina longicollis', emoji: '🐍', difficulty: '中〜上級', size: 'M（20〜28cm）', cites: null, legal: null,
    reason: 'オーストラリア産の曲頸類。首が長く蛇のように素早く動く。甲羅に引っ込めず横に曲げる独特の防御行動が印象的。',
    specs: { '最大甲長': '28cm', '水槽サイズ': '60cm〜', '水温': '20〜28℃', '難易度': '★★★' },
    coreSpecs: { size: '28cm', temp: '20〜28℃', lifespan: '20〜40年', diet: '肉食（魚・エビ中心）' },
    extraSpecs: { tankSize: '60cm〜' },
    links: [{ label: 'スッポン・ヘビクビガメ 飼育ガイド', href: '../guide-softshell.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.snakeneck||0) >= 2; },
    score: function(s){ return (s.snakeneck||0)+(s.intermediate||0)+(s.accessible||0)*2; }
  },
  { name: 'ジーベンロックナガクビガメ', latin: 'Macrochelodina rugosa', emoji: '🌊', difficulty: '上級', size: 'L（25〜35cm）', cites: null, legal: null,
    reason: 'オーストラリア北部産の大型曲頸類。頑丈な甲羅と大きなサイズが特徴。水中生活が主体で大型水槽が必要な本格派。',
    specs: { '最大甲長': '35cm', '水槽サイズ': '90cm〜', '水温': '24〜30℃', '難易度': '★★★' },
    coreSpecs: { size: '35cm', temp: '24〜30℃', lifespan: '20〜40年', diet: '肉食寄り雑食' },
    extraSpecs: { tankSize: '90cm〜' },
    links: [{ label: 'スッポン・ヘビクビガメ 飼育ガイド', href: '../guide-softshell.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.snakeneck||0) >= 2 && (s.budget_high||0) >= 2; },
    score: function(s){ return (s.snakeneck||0)+(s.advanced||0)+(s.budget_high||0)+(s.expert||0)+(s.ultra_rare||0); }
  },
  { name: 'アフリカヨコクビガメ', latin: 'Pelomedusa subrufa', emoji: '🌍', difficulty: '中〜上級', size: 'M（15〜25cm）', cites: null, legal: null,
    reason: 'サハラ以南に広く分布する曲頸類。比較的安価で入手しやすくなっている。横に首を曲げる独特の行動が面白い。水棲傾向が強い。',
    specs: { '最大甲長': '25cm', '水槽サイズ': '60cm〜', '水温': '24〜29℃', '難易度': '★★☆' },
    coreSpecs: { size: '25cm', temp: '24〜29℃', lifespan: '20〜40年', diet: '雑食' },
    extraSpecs: { tankSize: '60cm〜' },
    links: [{ label: 'スッポン・ヘビクビガメ 飼育ガイド', href: '../guide-softshell.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.snakeneck||0) >= 1 && (s.budget_low||0) >= 2; },
    score: function(s){ return (s.snakeneck||0)+(s.intermediate||0)+(s.budget_low||0)+(s.accessible||0)*2; }
  },
  { name: 'ヒラリーカエルガメ', latin: 'Phrynops hilarii', emoji: '🐸', difficulty: '上級', size: 'L（30〜40cm）', cites: null, legal: null,
    reason: '南米産曲頸類で流通量が多く、飼育もしやすい入門的曲頸種。下顎のヒゲ状突起がユーモラス。大型になるが水質・水温への許容範囲が広い。2025CB流通確認済み。',
    specs: { '最大甲長': '40cm', '水槽サイズ': '90cm〜', '水温': '20〜28℃', '難易度': '★★★' },
    coreSpecs: { size: '40cm', temp: '20〜28℃', lifespan: '20〜40年', diet: '雑食' },
    extraSpecs: { tankSize: '90cm〜' },
    links: [{ label: 'スッポン・ヘビクビガメ 飼育ガイド', href: '../guide-softshell.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.snakeneck||0) >= 2 && (s.budget_high||0) >= 1; },
    score: function(s){ return (s.snakeneck||0)+(s.budget_high||0)+(s.advanced||0)+(s.accessible||0); }
  },
  { name: 'パーケリーナガクビガメ', latin: 'Chelodina parkeri', emoji: '🦅', difficulty: '上級', size: 'M（20〜25cm）', cites: null, legal: null,
    reason: 'ナガクビガメ属の中で最も精悍な顔つきと評されるニューギニア産。EUCB流通あり。色抜け個体は非常に美しく、曲頸類の中でも上位の観賞価値を持つ。',
    specs: { '最大甲長': '25cm', '水槽サイズ': '60cm〜', '水温': '24〜30℃', '難易度': '★★★' },
    coreSpecs: { size: '25cm', temp: '24〜30℃', lifespan: '20〜40年', diet: '雑食' },
    extraSpecs: { tankSize: '60cm〜' },
    links: [{ label: 'スッポン・ヘビクビガメ 飼育ガイド', href: '../guide-softshell.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.snakeneck||0) >= 2 && (s.budget_high||0) >= 2; },
    score: function(s){ return (s.snakeneck||0)+(s.budget_high||0)+(s.advanced||0)+(s.expert||0)+(s.collector_grade||0); }
  },
  { name: 'アマゾンマタマタ', latin: 'Chelus orinocensis', emoji: '🌿', difficulty: '上級', size: 'L（35〜45cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: 'オリノコ川水系産のマタマタ近縁種。外見はマタマタに酷似するが別種。CITES II。究極の枯れ葉擬態カメをコレクションに加えたい上級者向き。',
    specs: { '最大甲長': '45cm', '水槽サイズ': '90cm〜', '水流': '極弱', '水温': '26〜30℃' },
    coreSpecs: { size: '45cm', temp: '26〜30℃', lifespan: '20〜40年', diet: '肉食（待ち伏せ捕食）' },
    extraSpecs: { tankSize: '90cm〜', waterFlow: '極弱' },
    links: [{ label: '水棲ガメ 飼育ガイド', href: '../guide-water-full.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.snakeneck||0) >= 2 && (s.budget_max||0) >= 2; },
    score: function(s){ return (s.snakeneck||0)+(s.budget_max||0)+(s.advanced||0)+(s.expert||0)+(s.ultra_rare||0); }
  },
  { name: 'サソリドロガメ', latin: 'Kinosternon scorpioides', emoji: '🦂', difficulty: '上級', size: 'L（17〜27cm）', cites: null, legal: null,
    reason: 'ドロガメ属最大種。中南米広域に分布し複数の亜種が知られる。噛みつき力が非常に強く取り扱いに注意が必要。大型ドロガメ系の迫力と個性を楽しみたいマニア向き。',
    specs: { '最大甲長': '27cm', '水槽サイズ': '90cm〜', '水温': '24〜30℃', '難易度': '★★★' },
    coreSpecs: { size: '27cm', temp: '24〜30℃', lifespan: '20〜40年', diet: '雑食' },
    extraSpecs: { tankSize: '90cm〜' },
    links: [{ label: '半水棲ガメ 飼育ガイド', href: '../guide-semi.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.large_mud||0) >= 2 && (s.advanced||0) >= 2; },
    score: function(s){ return (s.large_mud||0)+(s.advanced||0)+(s.budget_high||0)+(s.collector_grade||0); }
  },
  { name: 'スジオオニオイガメ', latin: 'Staurotypus salvinii', emoji: '💪', difficulty: '上級', size: 'L（25〜38cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: 'ドロガメ科最大クラス。噛みつき力が極めて強く素手での取り扱い厳禁。CITES II。大型ドロガメ系の究極形として国内での飼育者もいる本格マニア向き種。',
    specs: { '最大甲長': '38cm（メス）', '水槽サイズ': '90cm〜', '水温': '24〜30℃', '難易度': '★★★' },
    coreSpecs: { size: '38cm（メス）', temp: '24〜30℃', lifespan: '20〜40年', diet: '雑食' },
    extraSpecs: { tankSize: '90cm〜' },
    links: [{ label: '半水棲ガメ 飼育ガイド', href: '../guide-semi.html' }], asin: null,
    slug: 'giant-musk-turtle', hasPage: true,
    match: function(s){ return (s.large_mud||0) >= 3 && (s.advanced||0) >= 2; },
    score: function(s){ return (s.large_mud||0)+(s.advanced||0)+(s.budget_high||0)+(s.expert||0)+(s.ultra_rare||0); }
  },
  { name: 'マッコードナガクビガメ', latin: 'Chelodina mccordi', emoji: '🌿', difficulty: '上級', size: 'M（22〜26cm）', cites: 'CITES II', legal: 'cites_ii',
    reason: 'インドネシア・ロティ島固有の曲頸類。野生個体数が激減しており国内ではCB個体のみ流通。首が長い独特のシルエットが魅力。水温・水質管理が重要な上級者向け希少種。CITES II。',
    specs: { '最大甲長': '26cm', '水槽サイズ': '60〜90cm', '水温': '25〜30℃', '難易度': '★★★' },
    coreSpecs: { size: '26cm', temp: '25〜30℃', lifespan: '20〜30年', diet: '雑食（動物食寄り）' },
    extraSpecs: { tankSize: '60〜90cm' },
    links: [{ label: 'スッポン・ヘビクビガメ 飼育ガイド', href: '../guide-softshell.html' }], asin: null,
    slug: null, hasPage: false,
    match: function(s){ return (s.snakeneck||0) >= 2 && (s.budget_max||0) >= 1; },
    score: function(s){ return (s.snakeneck||0)+(s.advanced||0)+(s.budget_max||0)+(s.expert||0)+(s.ultra_rare||0)*2+(s.collector||0); }
  }
],

// ==================== 全カテゴリルート（動的生成） ====================
// allカテゴリは重複管理を廃止し、動的getter に変更（2026-06-24 DB構造修正）
  get all() {
    return this.land.concat(this.aquatic, this.forest, this.exotic);
  }

}; // end SPECIES
